### ISSUE TITLE
Unitary transformation of Z tensor Z

### ISSUE THREAD

**Issue by jjgoings** [MicrosoftDocs/quantum-docs-pr#1008]
The page says that "Similar to the one-qubit case, all two-qubit Pauli-measurements can be written as $U^\dagger (Z\otimes \id) U$ for $4\times 4$ unitary matrices $U$"

While this holds for the first few Pauli measurements and unitary transformations in the table, it does not seem to hold beginning at $Z\otimes Z$. In that case,

$Z\otimes Z \neq \operatorname{CNOT}_{10}^{\dagger} (Z\otimes \id) \operatorname{CNOT}_{10}$

however, 

$Z\otimes Z = \operatorname{CNOT}_{10}^{\dagger} (\id \otimes Z) \operatorname{CNOT}_{10}$

is there an error here, or am I missing something? I cannot get the math to work out for the other transformations involving CNOT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fa8b49-db57-3ecb-0f9b-9e32feee3ebc
* Version Independent ID: bc76d802-3855-b0ce-4131-f44852e7d419
* Content: [Pauli Measurements - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements)
* Content Source: [articles/concepts/pauli-measurements.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/pauli-measurements.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by jjgoings** [comment]
The math for the remaining unitary transformations work out for the "correlated" qubit tenor products by replacing CNOT10 with SWAP\cdotCNOT10

**Comment by geduardo** [comment]
HI @jjgoings. Thanks for filling the issue. Are you sure that you're using the correct form of CNOT10 when doing the calculations? Recall that the 4x4 matrix representation for the  CNOT10 in the basis used in the documentation is:

[1, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 1, 0, 0]

Since it uses the second qubit as control. I did some calculations and I got the results that are commented on the documentation. Tell me if this solves your problem, if not I can share with you my calculations.

**Comment by jjgoings** [comment]
Hi @geduardo,

Sounds like I was using the wrong CNOT10! If I use the representation you give, there are no issues.

I apologize, I got confused because I was relying on the definitions [here](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.cnot) and [here](https://docs.microsoft.com/en-us/quantum/concepts/multiple-qubits). I think it would have been helpful to see the definition for CNOT10 explicitly.

**Comment by cgranade** [comment]
@jjgoings: The definitions you link to are both examples of CNOT controlled on the first qubit and targeting the second (i.e.: CNOT₀₁). To get CNOT controlled on the second qubit and targeting the first, you need to conjugate with swaps.

```Q#
// The following is equivalent to CNOT(qs[1], qs[0]):
within {
    SWAP(qs[0], qs[1]);
} apply {
    CNOT(qs[0], qs[1]);
}
```

Once you conjugate by SWAP operations in that way, you should get the right form for CNOT₁₀ using the unitary matrices for SWAP and CNOT₀₁.

**Comment by jjgoings** [comment]
Awesome, thanks for clearing that up for me @cgranade and @geduardo! I guess that resolves the issue, and I learned something new today :)
It would still be helpful for novices like me to have a "hint" in the page to remind me that in general CNOT = CNOT01, and here we are using CNOT10 (which, granted, is made explicit, but I couldn't the matrix definition in the docs).

**Comment by geduardo** [comment]
Yes, we are working on refactoring the linear algebra section to clarify things like this. Stay tuned!
