### ISSUE TITLE
Minor Correction

### ISSUE THREAD

**Issue by haythamallos** [MicrosoftDocs/quantum-docs-pr#1011]
[Enter feedback here]
In document, it states the following:
"... Add the following operation to the Bell.qs file, inside the namespace, after the end of the SetQubitState operation:"

The actual file is called "Program.qs".  It was not renamed since creating the project.  May want to correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e984fdb6-63e6-92ac-f794-8a15a5092559
* Version Independent ID: bcd9a2e2-0b07-514e-5b43-8b3e092669ce
* Content: [Explore entanglement with Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/tutorials/explore-entanglement)
* Content Source: [articles/tutorials/explore-entanglement.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/tutorials/explore-entanglement.md)
* Product: **quantum**
* GitHub Login: @geduardo
* Microsoft Alias: **v-edsanc@microsoft.com**

**Comment by geduardo** [comment]
Thank you for filling the issue! Yes, you're right. That name was the previous name of the file in an older version of the tutorial and that line didn't get changed.  I'll fix it.
