### ISSUE TITLE
Wrong Q# sequence in MeasureY

### ISSUE THREAD

**Issue by thomasklingler** [MicrosoftDocs/quantum-docs-pr#1014]
I think that the Q# code for 'operation MeasureY(qubit : Qubit)' contains an error: 'Adjoint S(q)' should occur before 'H(q)'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fa8b49-db57-3ecb-0f9b-9e32feee3ebc
* Version Independent ID: bc76d802-3855-b0ce-4131-f44852e7d419
* Content: [Pauli Measurements - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements)
* Content Source: [articles/concepts/pauli-measurements.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/pauli-measurements.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by geduardo** [comment]
Thank you for filling the issue! You are right. I opened a PR to fix it: https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1035

**Comment by cgranade** [comment]
As a future improvement, should we consider moving this into a Q# sample that can be unit tested?
