### ISSUE TITLE
[Broken link] the quickstart-guide link needs to be fixed

### ISSUE THREAD

**Issue by dongsin-kim** [MicrosoftDocs/quantum-docs-pr#1031]
[Enter feedback here]
Hi all,

At this sentence:
> Create a Codespaces environment. Please follow the `quickstart guide`. When creating the Codespace, we recommend to enter microsoft/Quantum in the "Git Repository" field to load QDK-specific settings.

`quickstart guide` directs [the link](https://docs.microsoft.com/en-us/visualstudio/codespaces/browser). Unfortunately, I would think that the link is broken. ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e509ca-7867-e8f0-45f1-bb20d27ad232
* Version Independent ID: a6a281f8-53e0-8bdb-2b6e-8228fc2204f2
* Content: [Develop with Q# applications - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode&source=docs)
* Content Source: [articles/quickstarts/install-command-line.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/install-command-line.md)
* Product: **quantum**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by gillenhaalb** [comment]
Thanks for heads up! Found the error in the link (the actual link is https://docs.microsoft.com/en-us/visualstudio/codespaces/quickstarts/browser), and fixing it now.
