### ISSUE TITLE
No documentation available for "within/apply" statements.

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#1034]
I noticed that we don't have any explanation (or at least that I could find) on the statement `within{} apply{}` used in some parts of our documentation (ej: https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/operations-functions#conjugations).

I guess it probably should be placed in the Workflow section of the Q# user guide. 

Do you know where I could find more information about this statement to add some documentation? @gillenhaalb @cgranade

**Comment by cgranade** [comment]
Is this duplicated with https://github.com/MicrosoftDocs/quantum-docs-pr/issues/939?

**Comment by gillenhaalb** [comment]
@geduardo As far as I know, that section is the only explanation we have on it. Indeed, I think it fits better in Control Flow (will continue discussion in #939). Besides that, what sort of further explanation are you imagining?

**Comment by geduardo** [comment]
True! I forgot about that whole thread, my bad! Closing.
