### ISSUE TITLE
Empty Tuple Code Sample in Entanglement Tutorial

### ISSUE THREAD

**Issue by kchatr** [MicrosoftDocs/quantum-docs-pr#1046]
While explaining the `Unit `keyword, it made a reference to an empty tuple in Python which was followed by this code sample:
`(Tuple[()])`. However, this is incorrect, as an empty tuple can be initialized by either `tuple()` or `tuple([])`, but _not_ `Tuple[()]`

This is a relatively minor issue, but considering the nature of the documentation and rigour of the material, I feel like this is a valid albeit inconsequential issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f20167-a5ab-1b18-feca-17f4ffd7d1e3
* Version Independent ID: ef2aa8d4-af46-57ee-567e-12f23eeb0822
* Content: [Explore entanglement with Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/tutorials/explore-entanglement)
* Content Source: [articles/tutorials/explore-entanglement.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/tutorials/explore-entanglement.md)
* Product: **quantum**
* GitHub Login: @geduardo
* Microsoft Alias: **v-edsanc@microsoft.com**

**Comment by geduardo** [comment]
Oh, good catch! I'll create a PR to fix it.

**Comment by cgranade** [comment]
> Oh, good catch! Thanks @kchatr, I'll create a PR to fix it.

As a clarification, `Tuple[()]` is the [type hint](https://www.python.org/dev/peps/pep-0484/) for the value `tuple([])`.

**Comment by geduardo** [comment]
Oh, my bad @cgranade. Tbh, this is the first time I hear about "type hints". Cool that something like that exists!

**Comment by kchatr** [comment]
@geduardo Thanks! Do you mind if I create a pull request for this issue? Would love to contribute :)
