### ISSUE TITLE
Lenny-QC

### ISSUE THREAD

**Issue by lnelson1875** [MicrosoftDocs/quantum-docs-pr#1054]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16ca17e0-4031-faef-fc0d-b1406d3b778f
* Version Independent ID: d4b5084c-9c36-3321-5712-0ed8675d2427
* Content: [Understanding quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/overview/understanding-quantum-computing)
* Content Source: [articles/overview/understanding-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/overview/understanding-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by KittyYeungQ** [comment]
No feedback is provided in the issue
