### ISSUE TITLE
Code sample for LocalRotationsLayer?

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#1085]
Originally written by @mechpaul

https://docs.microsoft.com/en-us/quantum/user-guide/libraries/machine-learning/design

This documentation makes a reference to the LocalRotationsLayer instead of using ControlledRotation, but it doesn't provide any example or point to any example where LocalRotationsLayer is used. Could this documentation be updated to provide an example?

**Comment by geduardo** [comment]
Hi @mechpaul, in [this sample](https://docs.microsoft.com/en-us/samples/microsoft/quantum/training-sequential-models-with-q-using-built-in-datasets/) you can see how the function is implemented to design a circuit.

**Comment by Bradben** [comment]
Fixed
