### ISSUE TITLE
Add qsharp-language to repo list

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#1089]
Should this page also have a link to the  [qsharp-language](https://github.com/microsoft/qsharp-language) repo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592d8d18-eb52-7018-f128-41b6a7934604
* Version Independent ID: 5850b45d-123b-8e41-c46a-b0e357c806a7
* Content: [Contributing to the Microsoft Quantum Development Kit - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/resources/contributing/)
* Content Source: [articles/resources/contributing/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/resources/contributing/index.md)
* Product: **quantum**
* GitHub Login: @cgranade 
* Microsoft Alias: **chgranad**

**Comment by geduardo** [comment]
Hi @crazy4pi314, thanks for filling the issue. Yes, and it's already incorporated into the main branch from a past PR (https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1081)! So the link should appear in the next Live update.
