### ISSUE TITLE
Instructions for creating a new Q# project in VS Code are not clear

### ISSUE THREAD

**Issue by samarsha** [MicrosoftDocs/quantum-docs-pr#1105]
In the "Develop for Q#" section, the VS Code instructions say:

> To create a new project:
>
> 1. Click View -> Command Palette and select Q#: Create New Project.
> 2. Click Standalone console application.
> 3. Navigate to the location to save the project and click Create Project.
> 4. When the project is successfully created, click Open new project... in the lower right.

Following these instructions literally causes the "Create Project" button to do nothing. The dialog window actually wants you to type in the name of the new project folder in the "Filename" textbox, so just navigating to the location isn't enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e509ca-7867-e8f0-45f1-bb20d27ad232
* Version Independent ID: a6a281f8-53e0-8bdb-2b6e-8228fc2204f2
* Content: [Develop with Q# applications in an IDE - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode#develop-with-q)
* Content Source: [articles/quickstarts/install-command-line.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/install-command-line.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by ricardo-espinoza** [comment]
Assigning this to myself.
