### ISSUE TITLE
Z gate error

### ISSUE THREAD

**Issue by venkatn93** [MicrosoftDocs/quantum-docs-pr#1112]
[Enter feedback here]
In this page you have in the last formula Z^(f(0)−f(1)) when I think this should be Z^(f(1)−f(0)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4959bf-caf5-9030-73a2-3910b8a0788e
* Version Independent ID: 3a6ff78b-19a7-f824-5783-8015c047b6bc
* Content: [Quantum oracles - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/oracles)
* Content Source: [articles/concepts/oracles.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/oracles.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by cgranade** [comment]
I believe it should work either way, since 𝑍⁻¹ = 𝑍⁺ = 𝑍 (that is, `Adjoint Z` is the same operation as `Z`). Nonetheless, we definitely appreciate the feedback as to readability of the article. I'll go on and flag this to the docs team for awareness. Thanks for raising the issue!

**Comment by geduardo** [comment]
I'll keep this issue open for our new tech writers joining this week  @cgranade ;)

**Comment by venkatn93** [comment]
Thanks for the explanation @cgranade !

**Comment by SoniaLopezBravo** [comment]
I agree to @cgranade. Notice that f(x) is a Boolean function, so $f(0)-f(1) \in {0,1,-1}$. Since Pauli Z is an orthogonal matrix  $Z^(-1) = Z^(T) = Z$ in this case it works either way.
