### ISSUE TITLE
typo in PE without eigenstates

### ISSUE THREAD

**Issue by vivienlonde** [MicrosoftDocs/quantum-docs-pr#1115]
Hello, I think there is a typo in the non-unitary transformation of Iterative Phase Estimation without eigenstates.
In my opinion, the denominator should be:

$$ \sqrt{ \sum_k \Pr(\phi_k) \Pr( \text{Result} \vert \phi_k ) } $$

(Using twice the same dummy index for summations makes it hard to read).
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd460263-377c-8a0a-c707-abea4754ff8c
* Version Independent ID: 46e0a7aa-a933-a899-ddaa-118387faca7b
* Content: [Quantum characterization and statistics - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/libraries/standard/characterization#iterative-phase-estimation)
* Content Source: [articles/user-guide/libraries/standard/characterization.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/libraries/standard/characterization.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **martinro**

**Comment by SoniaLopezBravo** [comment]
Hi! You are right, using the same dummy index leads to confusion. In fact the denominator in this equation is correct but for sake of clarity it should be $ \sqrt{ \Pr(\phi_k) sum_k \Pr( \text{Result} \vert \phi_k ) } $ while $sum_j$ in the rest.

**Comment by geduardo** [comment]
Can you create a PR to fix it @SoniaLopezBravo?

**Comment by SoniaLopezBravo** [comment]
Done!

**Comment by Bradben** [comment]
Fixed in PR 1150
