### ISSUE TITLE
VS Code and VS Studio Icons/Titles are mixed up.

### ISSUE THREAD

**Issue by richardj99** [MicrosoftDocs/quantum-docs-pr#1117]
![image](https://user-images.githubusercontent.com/27011477/99916784-10ce3280-2d04-11eb-97fd-bb4d30f5559e.png)

I think these are meant to be the other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Setting up the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/)
* Content Source: [articles/quickstarts/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/index.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by geduardo** [comment]
Yup, you're right! Thank you very much for filling this issue. I opened a PR to fix this: https://github.com/MicrosoftDocs/quantum-docs-pr/pull/1118
