### ISSUE TITLE
"This Page" feedback button directs to wrong repo

### ISSUE THREAD

**Issue by guenp** [MicrosoftDocs/quantum-docs-pr#1120]
If I scroll to the bottom of any API docs page (for example, https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.addconstantfxp), and click on the "Submit and view feedback for This Page" button, I am redirected to create an issue in the [Quantum](http://github.com/microsoft/Quantum) repo. This delays the process for us to discover these issues.

Tag @msoeken @cgranade 

![Screenshot 2020-11-23 091921](https://user-images.githubusercontent.com/4041805/99993826-11e77a00-2d6d-11eb-89d5-0cae3b8965ec.png)

![Screenshot 2020-11-23 091933](https://user-images.githubusercontent.com/4041805/99993833-1318a700-2d6d-11eb-8aa5-d0966be5d4ee.png)

**Comment by cgranade** [comment]
This can be modified in the config file at https://github.com/MicrosoftDocs/quantum-docs-pr/blob/main/api/docfx.json#L42. In any case, since content under the API docset can come from either quantumlibraries, quantum-nc, or qsharp-runtime (depending on the specific function, operation, or UDT being documented), the thinking was that making feedback issues go to a repo that is at least in the right organization (i.e.: microsoft, as opposed to microsoftdocs as is used for feedback about conceptual docs) lets us triage and move issues accordingly.

**Comment by guenp** [comment]
@cgranade, I see, thanks for clarifying. Would it be possible to add another button, one for raising an issue about the formatting (which can redirect to `quantum-docs-pr`), and one about the content (which can redirect to `QuantumLibraries`)?

**Comment by cgranade** [comment]
> @cgranade, I see, thanks for clarifying. Would it be possible to add another button, one for raising an issue about the formatting (which can redirect to `quantum-docs-pr`), and one about the content (which can redirect to `QuantumLibraries`)?

Not that I'm aware of, no, but @Bradben may know more.

**Comment by Bradben** [comment]
No, unfortunately. There are some things you can customize (like which folders go to which product pages), but the button layout and wording is fixed.

**Comment by guenp** [comment]
Ok, thanks @Bradben. It looks like indeed everything in the `/api` folder currently has `feedback_github_repo` set to the `Quantum` repo and it seems like it's not possible to add more granularity here. In that case I would suggest to resolve this issue by changing this setting to `QuantumLibraries`, instead and triaging to `quantum-docs-pr`, `quantum-nc` or `qsharp-runtime` from there. I'm happy to open a PR if this works for everyone.

**Comment by Bradben** [comment]
That works for me. Do you see any other issues with this, @cgranade?  (FYI - there are currently build issues with the repo, which is why your PR is choking).

**Comment by cgranade** [comment]
No concerns from my end; we'll need to triage for several repos anyway, so may as well direct to the one where the majority of triaging should land. Since most of the API surface is in the Libraries repo, I agree with this change as well.
