### ISSUE TITLE
Examples from Q# Libraries API don't show up in docs

### ISSUE THREAD

**Issue by guenp** [MicrosoftDocs/quantum-docs-pr#1121]
There are two ways in which examples are currently formatted:
- `/// # Example` (see e.g. [All](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.all))
- Under `/// # Remarks`, `/// ## Example` (see e.g. [Fold](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.fold))

Neither methods currently show up in the generated docs.
Is this a bug or are we using the wrong formatting convention?

Tag: @msoeken @cgranade @KittyYeungQ

**Comment by cgranade** [comment]
> There are two ways in which examples are currently formatted:
> 
> * `/// # Example` (see e.g. [All](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.all))
> * Under `/// # Remarks`, `/// ## Example` (see e.g. [Fold](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arrays.fold))

As documented at https://docs.microsoft.com/en-us/quantum/resources/contributing/docs#contributing-to-the-api-references, the first form is correct. Some things still use the second method, as that predates support for the `/// # Example` header mentioned in that link and in the specs at https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/file-structure#documentation-comments.

> Neither methods currently show up in the generated docs.
> Is this a bug or are we using the wrong formatting convention?

Will need to investigate, but in any case, this is not a documentation bug but a qsharp-compiler issue.

**Comment by guenp** [comment]
Thanks @cgranade for taking quick action to resolve this issue! It looks like we'll need to refactor some of the code to make sure we are consistently using the `/// # Example` formatting.
