### ISSUE TITLE
LaTeX formulas won't render in the PDF version

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#1125]
In the PDF version of the documentation, the LaTeX formulas won't render properly. 

Example:
![image](https://user-images.githubusercontent.com/48300381/100079810-66f6bf00-2e45-11eb-8530-ca257637b7ec.png)

**Comment by Bradben** [comment]
I think this is a limitation of the conversion tool that OPS uses (possibly Pandoc, which I know you have to set certain flags to get MathJax and LaTeX to render correctly in PDF). I turned off the PDF publishing option in the config until we can figure it out.
