### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by mikolajMacioszczyk** [MicrosoftDocs/quantum-docs-pr#1135]
[Enter feedback here]
In Metrics Reported section there is bug in Width description. The link redirects to Depth Counter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb2344ee-3afb-541f-65c2-a413b98c0c69
* Version Independent ID: 520e0a3a-3106-b422-48bf-1b15af0ad1b6
* Content: [Quantum resources estimator - Quantum Development Kit - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/machines/resources-estimator#metrics-reported)
* Content Source: [articles/user-guide/machines/resources-estimator.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/machines/resources-estimator.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **anpaz**

**Comment by geduardo** [comment]
Thank you for filling this issue! I created a PR to fix it.
