### ISSUE TITLE
IQ# magic commands don't have a list page

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#1145]
For Q# libraries APIs we have pages that list all operations in the namespace, such as [this one](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math). It would be really convenient to add a similar page for IQ# magic commands, so that the person who's looking to see what commands exist can see all of them in one place with summaries. (Currently I couldn't find a way to share a list of magic commands with somebody, other than by pointing to one command and suggesting to look at others in the manu.)

**Comment by rmshaffer** [comment]
Is this what you're looking for?
https://docs.microsoft.com/qsharp/api/iqsharp-magic/

**Comment by tcNickolas** [comment]
Yes, exactly! Is there a way to get there from TOC?

**Comment by rmshaffer** [comment]
Interesting, no, I don't see that page in the TOC. (But it is the first result when searching "iqsharp magic commands" in Google.)

There is however a very similar page accessible from TOC under **Q# user guide -> Quick reference -> IQ# magic commands**:
https://docs.microsoft.com/quantum/user-guide/quickref/iqsharp

**Comment by tcNickolas** [comment]
I see, I was looking for it near the commands docs itself, similar to other libraries
![image](https://user-images.githubusercontent.com/10113024/101390907-63692c00-3878-11eb-8e28-175ac3f55c48.png)

**Comment by rmshaffer** [comment]
I agree, there should certainly be a link to the overview page there.
https://docs.microsoft.com/qsharp/api/iqsharp-magic/

**Comment by cgranade** [comment]
Not directly a solution to the documentation issue, but as a possible workaround, the `%lsmagic` command from within IQ# itself can be helpful for finding a list of currently available IQ# magic commands.

**Comment by rmshaffer** [comment]
Transferring this to the IQ# repo, as that TOC is programmatically generated via code in https://github.com/microsoft/iqsharp/blob/main/build/docs/build_docs.py.
