### ISSUE TITLE
AssertQubitState requires explicit Complex() call

### ISSUE THREAD

**Issue by cpalmer2020** [MicrosoftDocs/quantum-docs-pr#276]
From Q# Language User Voice (ID:
34713733):

Example from documentation does not compile:
AssertQubitState(((1., 0.), (0., 0.)), qubits0, 1e-5);
However, this code does:
AssertQubitState((Complex(1., 0.), Complex(0., 0.)), qubits0, 1e-5);
Error being:
Severity Code Description
Error QS0001 Type mismatch for argument: (Microsoft.Quantum.Extensions.Math.Complex, Microsoft.Quantum.Extensions.Math.Complex) expected, but ((Double, Double), (Double, Double)) was provided 
Error QS0001 expected type Microsoft.Quantum.Extensions.Math.Complex, instead got type (Double, Double)
Error QS0001 expected type Microsoft.Quantum.Extensions.Math.Complex, instead got type (Double, Double)

**Comment by tcNickolas** [comment]
The documentation has been updated accordingly.
