### ISSUE TITLE
Bug in documentation about AssertQubitState

### ISSUE THREAD

**Issue by thilow** [MicrosoftDocs/quantum-docs-pr#279]
the example code in:
quantum-docs-pr/api/prelude/microsoft.quantum.extensions.testing.assertqubitstate.yml 
does not compile for me.

To make it work I had to:
* change pair of Doubles to Complex
* In second invocation of AssetQubitState change from qubits[0] to qubits[1] (From context I guess the idea was that both assertions should not fail)

Thanks!

**Comment by tcNickolas** [comment]
The documentation has been updated to fix both these issues. Thank you!
