### ISSUE TITLE
Trying to help with code documentation for the Bell example!

### ISSUE THREAD

**Issue by Horaddrim** [MicrosoftDocs/quantum-docs-pr#284]
Hi guys! What a wonderful work in the Quantum quick start projects and the Q# overall documentation!
Really congratulations! 

So, I'm here because, while I was studying and trying to understand the bell example code, I written down a LOT of comments, so after I've finished, I just figure it out that maybe it can be useful for someone else, but I don't know where to post it to help you guys, so that's why I'm opening this issue!
I've documented in a personal [repo](https://github.com/Horaddrim/quantum-bell) so, If you guys want to take a look at the [`Bell.qs`](https://github.com/Horaddrim/quantum-bell/blob/master/Bell.qs) file, maybe can help to be in the official docs :sparkling_heart:

**Comment by anpaz-msft** [comment]
Thanks for reaching out.
I took a quick look at your repo and agree it can be useful for other people. Thanks for sharing!
Our documentation and samples are all open source. You should consider submitting a PR if you see an area that needs improvement and you feel you can contribute.
On top of the documentation and samples, we also have [another repo with *quantum katas* 
](https://github.com/Microsoft/QuantumKatas) which are a series of self-paced tutorials aimed at teaching you elements of quantum computing and Q# programming at the same time. You should check them out: https://github.com/Microsoft/QuantumKatas.
And a final note, I feel I should clarify a couple of things from the comments in your code:
1. `CNOT` does not generate entanglement by itself. A combination of `H` and `CNOT` does.
2. `M` is short for measurement, and you're right, it is equivalent to "observing" (or measure) the quantum state.

Thanks again!
