### ISSUE TITLE
Documentation issue in Quantum circuit section

### ISSUE THREAD

**Issue by vageesh** [MicrosoftDocs/quantum-docs-pr#293]
In the section  [Quantum Circuits ](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quantum-concepts-8-QuantumCircuits.md#quantum-circuits), shouldn't $\text{ CNOT}_{01}(H\otimes 1)$ actually be $\text{ CNOT}_{01}(1\otimes H)$ for creating maximally entangled two-qubit state ?

**Comment by tcNickolas** [comment]
This depends on the convention used for indices in the tensor product, and I think there are two different ones. Hadamard gate needs to be applied to the qubit 0 which then acts as a control for the CNOT gate, and identity gate needs to be applied to the qubit 1.

**Comment by cgranade** [comment]
I think that @tcNickolas is right that the documentation is correct as written, so closing for now. Please let us know if there's something else that would help clarify and we'll reopen.
