### ISSUE TITLE
Fix installation instructions for Linux?

### ISSUE THREAD

**Issue by ebraminio** [MicrosoftDocs/quantum-docs-pr#326]
Hey there, I followed installation instructions on [for Linux](https://docs.microsoft.com/en-us/quantum/install-guide/vs-code?view=qsharp-preview) by installing `sudo apt-get install dotnet-sdk-2.1` and issuing `dotnet new -i "Microsoft.Quantum.ProjectTemplates::0.3.1811.203-preview"` and it says

```
$ dotnet new -i "Microsoft.Quantum.ProjectTemplates::0.3.1811.203-preview"
  Restoring packages for /home/ebrahim/.templateengine/dotnetcli/v2.1.500/scratch/restore.csproj...
  Installing Microsoft.Quantum.ProjectTemplates 0.3.1811.203-preview.
  Generating MSBuild file /home/ebrahim/.templateengine/dotnetcli/v2.1.500/scratch/obj/restore.csproj.nuget.g.props.
  Generating MSBuild file /home/ebrahim/.templateengine/dotnetcli/v2.1.500/scratch/obj/restore.csproj.nuget.g.targets.
  Restore completed in 193.76 ms for /home/ebrahim/.templateengine/dotnetcli/v2.1.500/scratch/restore.csproj.

Usage: new [options]

Options:
  -h, --help    
[...]
```

Maybe something I'm missing or it is not ".NET Core SDK 2.0 or _later_"?

**Comment by tcNickolas** [comment]
This looks rather similar to what I would expect from installing project templates. Have you tried creating a new project after this step (as in https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-vscode)?

**Comment by ebraminio** [comment]
Correct. Thanks
