### ISSUE TITLE
Maintain and update LaTeX notation

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#359]
There's a lot of small LaTeX rendering issues here and there caused by the DocFX -> MathJax pipeline that would be good to resolve. In particular, we've set up macros like `\ket`, `\bra`, and `\id` to help typeset different notation, such that relying more heavily on these macros can help make sure that things render consistently.

- [x] Replace `\left|\psi\right\rangle`-style notation with `\ket{\psi}` (same with bra)
- [x] Replace `\mathbb{1}` with `\id`
- [ ] Fix improperly escaped linebreaks

**Comment by gillenhaalb** [comment]
Opened a branch for this. Any chance you could point out an example of the improper escape?

The few spots where I didn't update the \xangle's was where the bra-ket is an inner product. The current \braket macro is defined as simply <x>, so it appears we need to define a new one for <x|y>. I tried for a bit but wasn't sure how to make the 2 argument macro in the JSON syntax.

**Comment by gillenhaalb** [comment]
@cgranade where do we stand with the linebreaks? Good to close the issue?

**Comment by cgranade** [comment]
I think so, yes. We haven't run into examples of lines running together recently, and can easily open more focused issues should we do so in the future.
