### ISSUE TITLE
Quantum docs pages missing useful github integration

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#376]
I was reading through the QDK online docs recently and noticed that there are a couple of features/buttons missing from the built docs pages. The feature to be able from the doc page to directly link back to the right file in this repo to make an edit/fix is really helpful, as well as the ability to see if there are open issues on a docs page without going directly to GitHub. You can see an example of this on other MSFT docs sites: https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019

There is 2 more buttons in the header,
![image](https://user-images.githubusercontent.com/6486256/55739231-82495800-59dd-11e9-9d11-27f1d96fa2d9.png)

and an embedded GitHub issue thing at the bottom.
![image](https://user-images.githubusercontent.com/6486256/55739323-adcc4280-59dd-11e9-9bc4-ede11a3a8664.png)

I feel like these used to exist on the QDK pages, but I am not sure.
Thanks!
Sarah

**Comment by cgranade** [comment]
@cpalmer2020, would you be able to suggest who we can assign this to? It'd be good to ensure that we continue to get feedback through the new GitHub-based system. Thanks!

**Comment by crazy4pi314** [comment]
Just bumping this, having the links would help a lot with some community stuff I want to do coming up (docs sprints).
Thanks! 💖

**Comment by tcNickolas** [comment]
I believe this has been fixed back in May in PR #419. 

![image](https://user-images.githubusercontent.com/10113024/66357401-879f4500-e923-11e9-94e0-be49bb83891f.png)

I agree that this is very convenient, thank you for bringing it up!
