### ISSUE TITLE
Unable to find package microsoft.quantum.iqsharp. No packages exist with this id

### ISSUE THREAD

**Issue by vpyvovar** [MicrosoftDocs/quantum-docs-pr#379]
![image](https://user-images.githubusercontent.com/37424613/55982344-972c2280-5c4d-11e9-8d08-864c7dd21108.png)

Briefly:
following instructions, cant install iqsharp.

in text:
C:\WINDOWS\system32>dotnet --list-sdks
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]

C:\WINDOWS\system32>dotnet tool install -g Microsoft.Quantum.IQSharp

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anon
ymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with
 the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment
variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establis
hing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
error NU1101: Unable to find package microsoft.quantum.iqsharp. No packages exist with this id in so
urce(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Packages
The tool package could not be restored.
Tool 'microsoft.quantum.iqsharp' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify th
e version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.****

**Comment by cgranade** [comment]
Thanks for the report! It looks like when you ran `dotnet tool install`, it didn't look at nuget.org to try and find the package. Would you be willing to share the contents of your `NuGet.Config` file? Typically that's under `AppData/Roaming/NuGet/NuGet.Config` in your user directory. Thanks!

**Comment by vpyvovar** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <disabledPackageSources>
 <add key="nuget.org" value="true" />
 <add key="OSS_All" value="true" />
<add key="SQL-Toolset" value="true" /> <add key="SQLIS-DP" value="true" />
 </disabledPackageSources>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
 <add key="OSS_All" value="https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v2" />
<add key="SQL-Toolset" value="https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v2" />
 <add key="SQLIS-DP" value="https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_DP/nuget/v2" />
 <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
   <packageSourceCredentials>
 <OSS_All>
 <add key="Username" value="VssSessionToken" />
 <add key="Password" value="xxx" />
 </OSS_All>
<SQL-Toolset>
 <add key="Username" value="VssSessionToken" />
 <add key="Password" value="xxx" />
 </SQL-Toolset>
 <SQLIS-DP>
 <add key="Username" value="VssSessionToken" />
 <add key="Password" value="xxx" />
 </SQLIS-DP>
 </packageSourceCredentials>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>

**Comment by vpyvovar** [comment]
\\scratch2\scratch\vipyvo\NugetConfigQuantumIssue

**Comment by j2jensen** [comment]
Based on the first bullet point in the message, I was able to get around this by specifying the version, as specified on [the NuGet page](https://www.nuget.org/packages/Microsoft.Quantum.IQSharp/). Currently:
```
dotnet tool install --global Microsoft.Quantum.IQSharp --version 0.7.1905.3109
```

**Comment by amirebrahimi** [comment]
This was a frustrating issue to track down and after doing all of the updates to VS and still not being able to install I tracked it down to an environment variable. Try removing `MSBuildSDKsPath` and see if that fixes your issue.

**Comment by sillysachin** [comment]
I upgraded to aspnetcore 3.1 https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio-mac

The issue gets resolved.

**Comment by KittyYeungQ** [comment]
Have seen this issue reported before. @gillenhaalb do you know if there is a resolution documented somewhere?

**Comment by gillenhaalb** [comment]
@cgranade @KittyYeungQ it looks like using .NET 3.1 resolved the issue. I'd say this is good to be closed then, considering that our install docs now list having at least 3.1 as a prerequisite
