### ISSUE TITLE
Update conceptual documentation to reflect 0.6 changes

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#384]
The conceptual documentation should be updated to reflect changes made as a part of the work on Microsoft/QuantumLibraries#35.

- [ ] Clarify that the canon is now a part of the Microsoft.Quantum.Standard package.
- [ ] Ensure that snippets in conceptual articles use the correct `open` statements.
- [ ] Update links to reference docs to make sure that they point to correctly merged documentation.

**Comment by gillenhaalb** [comment]
Fixed/checked in #672
