### ISSUE TITLE
Wrong formula in the description of PrepareEntangledState operation

### ISSUE THREAD

**Issue by vadym-kl** [MicrosoftDocs/quantum-docs-pr#423]
The formula that follows "prepares the maximally entangled state" is incorrect

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b3d14d-02db-e961-c376-d6977f1f2516
* Version Independent ID: ffb261c5-5ed8-f68f-d9a7-5bd01a58807d
* Content: [PrepareEntangledState operation (Microsoft.Quantum.Preparation)](https://docs.microsoft.com/en-gb/qsharp/api/qsharp/microsoft.quantum.preparation.prepareentangledstate?view=qsharp-preview#feedback)
* Content Source: [api/qsharp/microsoft.quantum.preparation.prepareentangledstate.yml](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.preparation.prepareentangledstate.yml)
* GitHub Login: @anpaz-msft

**Comment by tcNickolas** [comment]
I fixed the sources for the formula as part of https://github.com/microsoft/QuantumLibraries/pull/111 - once we update apidocs for 0.7 release the issue will be resolved. Thank you for pointing this out!
