### ISSUE TITLE
Add a link to nuget package update from Visual Studio

### ISSUE THREAD

**Issue by anpaz** [MicrosoftDocs/quantum-docs-pr#438]
For people using Visual Studio, we should point them to https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#updating-a-package for how to update a package within Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2cb8a12-0fe8-6b27-c3a6-c7d4b9a089f8
* Version Independent ID: b1ddff8c-781e-6b1b-604a-01bb5207f897
* Content: [Getting Started with C# and Q#](https://docs.microsoft.com/en-us/quantum/install-guide/csharp?view=qsharp-preview#update)
* Content Source: [articles/install-guide/csharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csharp.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **anpaz@microsoft.com**

**Comment by Bradben** [comment]
Process is in https://docs.microsoft.com/en-us/quantum/user-guide/libraries/additional-libraries?tabs=tabid-csproj - needed in install topic?
