### ISSUE TITLE
Invalid xref in document

### ISSUE THREAD

**Issue by anpaz-msft** [MicrosoftDocs/quantum-docs-pr#442]
1 invalid cross reference(s) ""&lt;xref:microsoft.quantum.canon.preparearbitrarystate&gt;"".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fdb561b-2759-d054-45db-e1c3e1c00ad1
* Version Independent ID: c68ed36c-bd81-40f7-d38f-b9d7272c93da
* Content: [Simulating Hamiltonian Dynamics](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/concepts/algorithms?view=qsharp-preview)
* Content Source: [articles/libraries/chemistry/concepts/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/concepts/algorithms.md)
* Product: **quantum**
* GitHub Login: @nathanwiebe2
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by tcNickolas** [comment]
This has been fixed in #525. Thank you for reporting it!
