### ISSUE TITLE
Invalid xrefs in second quantization

### ISSUE THREAD

**Issue by anpaz-msft** [MicrosoftDocs/quantum-docs-pr#443]
2 invalid cross reference(s) "&lt;xref:Microsoft.Quantum.Chemistry.LadderOperators.LadderOperator&gt;", "&lt;xref:Microsoft.Quantum.Chemistry.LadderOperators.LadderSequence&gt;".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caec099a-31c7-67a1-a291-75356dc6f478
* Version Independent ID: bc5bf80c-aa3b-303e-a2a0-a603407cc26c
* Content: [Second Quantization](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/concepts/second-quantization?view=qsharp-preview)
* Content Source: [articles/libraries/chemistry/concepts/second-quantization.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/concepts/second-quantization.md)
* Product: **quantum**
* GitHub Login: @nathanwiebe2
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by tcNickolas** [comment]
This also has been fixed in #525. Thank you for reporting!
