### ISSUE TITLE
Invalid xref

### ISSUE THREAD

**Issue by anpaz-msft** [MicrosoftDocs/quantum-docs-pr#444]
1 invalid cross reference(s) ""&lt;xref:microsoft.quantum.canon.multim&gt;"".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b49265-01d4-14a7-6f5a-e9ba694eb84f
* Version Independent ID: a3f1f416-68eb-0f14-78b4-086ef74bdbb6
* Content: [Q# standard libraries - prelude](https://docs.microsoft.com/en-us/quantum/libraries/standard/prelude?view=qsharp-preview)
* Content Source: [articles/libraries/standard/prelude.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/prelude.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

**Comment by tcNickolas** [comment]
This has been fixed in #525. Thank you for reporting it!
