### ISSUE TITLE
Invalid xref

### ISSUE THREAD

**Issue by anpaz-msft** [MicrosoftDocs/quantum-docs-pr#445]
1 invalid cross reference(s) ""microsoft.quantum.language.statements"".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 123a5b78-2045-8b83-5254-249c1f3b893c
* Version Independent ID: 7e83db9c-ded8-353a-6b73-0eeacf2bdd92
* Content: [Q# type model](https://docs.microsoft.com/en-us/quantum/language/type-model?view=qsharp-preview)
* Content Source: [articles/language/type-model.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/language/type-model.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by anpaz-msft** [comment]
Never mind, invalid doc's build warning.

**Comment by deonlewisduke** [comment]
Still relevant to the quantum effect I am here to have you all present as fact with the present as the last future, all existing, not existing and all amplitudes in-between. Where do I go to learn customized install of the final OS that doesn't exist yet? Or can I help write it? Or did I already, so I always will?

**Comment by deonlewisduke** [comment]
Found a misspelling on the doc.microsoft.com/quantum page. When I clicked it, it left me back here. Spelling error as follows.

Under User-Defined types. Microsoft.Quantum.Math namespace, for instance... For example we could have named the to(should read TWO) items [Re] as in "reply". And so I have.
