### ISSUE TITLE
an identity matrix/operator missing 

### ISSUE THREAD

**Issue by thesoulpole** [MicrosoftDocs/quantum-docs-pr#446]
please check the last equation ( "For example, if we wish to apply the 
X gate to the first qubit and then perform a CNOT between the second and third qubits we may express this transformation as"). The dimensions of the two sides of the equation are out of sync. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6516e6bf-4cd0-2d9b-4d18-565d7dbc38b6
* Version Independent ID: a5b54d5e-8b9a-f7d5-2dac-ecd515478ba5
* Content: [Multiple qubits](https://docs.microsoft.com/en-us/quantum/concepts/multiple-qubits?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/multiple-qubits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/multiple-qubits.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by tcNickolas** [comment]
Indeed the defined unitary acts on 6 qubits but the state is a product of 7 qubits. Good catch, I opened PR to fix it. Thank you!

**Comment by thesoulpole** [comment]
Super, thx:)

Pozdrawiam/Best Regards
Piotr Sienkiewicz

Sent from my mobile thingy

On 14 Jun 2019, at 00:02, Mariia Mykhailova <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #446<https://github.com/MicrosoftDocs/quantum-docs-pr/issues/446>.

**Comment by thesoulpole** [comment]
Thx!

Pozdrawiam/Best Regards
Piotr Sienkiewicz

Sent from my mobile thingy

On 14 Jun 2019, at 00:02, Mariia Mykhailova <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #446<https://github.com/MicrosoftDocs/quantum-docs-pr/issues/446>.
