### ISSUE TITLE
Refactor linear algebra article to provide more Q# examples

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#465]
At the moment, the current [linear algebra conceptual article](https://docs.microsoft.com/quantum/concepts/vectors-and-matrices) doesn't really connect out to how linear algebra is used in Q#. Using DumpMachine / DumpRegister and so forth should make it easier to integrate Q# examples into the conceptual documentation and make it more clear how linear algebra is used to specify the behavior of Q# operations.

(h/t @haishi2016 for raising this issue at microsoft/QuantumLibraries#134)

**Comment by gillenhaalb** [comment]
@cgranade I think this might coincide very well with a more in-depth explanation of the full-state simulator (that I'm hoping to get to in the future). I definitely agree, there's a lot of learning potential in DumpMachine, the surface of which I only scratched at the end of the tutorial PR (#551)

**Comment by cgranade** [comment]
Makes sense! With the new Jupyter display features that landed in microsoft/iqsharp#81, that could be a nice place to include some screenshots as well.

**Comment by Bradben** [comment]
Also see issue #782
