### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by zhengyq95** [MicrosoftDocs/quantum-docs-pr#471]
In **Installation** section, the command
```bash
dotnet new console -lang Q# -o myApp
cd MyApp
dotnet run
```
has a typo, you should write `cd myApp`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2cb8a12-0fe8-6b27-c3a6-c7d4b9a089f8
* Version Independent ID: b1ddff8c-781e-6b1b-604a-01bb5207f897
* Content: [Getting Started with C# and Q#](https://docs.microsoft.com/en-us/quantum/install-guide/csharp?view=qsharp-preview)
* Content Source: [articles/install-guide/csharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csharp.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **anpaz@microsoft.com**

**Comment by cgranade** [comment]
Thanks for the report, @zhhhhxhq! We probably wrote that thinking of Windows, but that difference definitely matters on case-sensitive filesystems.
