### ISSUE TITLE
Python import qsharp error

### ISSUE THREAD

**Issue by patrickxli** [MicrosoftDocs/quantum-docs-pr#473]
When I import qsharp in Python, I see the following error:

import qsharp
Preparing Q# environment...
...................Traceback (most recent call last):

  File "<ipython-input-1-eeaf4e1dca22>", line 1, in <module>
    import qsharp

  File "D:\Anaconda3\lib\site-packages\qsharp\__init__.py", line 119, in <module>
    client = _start_client()

  File "D:\Anaconda3\lib\site-packages\qsharp\clients\__init__.py", line 47, in _start_client
    raise Exception("Q# environment was not available in allocated time.")

Exception: Q# environment was not available in allocated time.

How to fix it? Any advice?

Thanks!

Patrickxli
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25410f91-77bb-ae52-a0ff-5b2a379c4e63
* Version Independent ID: b89cfc22-7982-4fb3-53c2-d96baed0e3ad
* Content: [Getting Started with Python and Q#](https://docs.microsoft.com/en-us/quantum/install-guide/python?view=qsharp-preview)
* Content Source: [articles/install-guide/python.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/python.md)
* Product: **quantum**
* GitHub Login: @cpalmer
* Microsoft Alias: **cpalmer@microsoft.com**

**Comment by cgranade** [comment]
Thanks for the report, @patrickxli! It looks like this isn't a documentation issue, but a possible issue with IQ# and the Python interoperability feature of the Quantum Development Kit, so I'll close this issue and reopen it there. Please feel free to chime in on the new issue. Thanks!
