### ISSUE TITLE
QCTraceSimulatorConfiguration field names are incorrect

### ISSUE THREAD

**Issue by jgukelberger** [MicrosoftDocs/quantum-docs-pr#475]
The field names have been renamed in the code but not on any of the doc pages. Even the auto-generated API docs still show the old names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 692ef3cc-32c9-9954-a833-5803baf2ebed
* Version Independent ID: ccf952ea-f884-425d-d324-a5c2c4cbc07f
* Content: [Depth Counter](https://docs.microsoft.com/en-us/quantum/machines/qc-trace-simulator/depth-counter?view=qsharp-preview)
* Content Source: [articles/machines/qc-trace-simulator/depth-counter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/machines/qc-trace-simulator/depth-counter.md)
* Product: **quantum**
* GitHub Login: @vadym-kl
* Microsoft Alias: **vadym@microsoft.com**

**Comment by jgukelberger** [comment]
ping @anpaz-msft

**Comment by KittyYeungQ** [comment]
@anpaz-msft Let me know if this was resolved since it was opened in Aug 2019.
