### ISSUE TITLE
Suggestion: New "Learning resources" section

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#487]
As a recent learner of Q# I found that there are a lot of learning resources but they are sparsed or not explained in the main website. For example, I've been reviewing the [main site](https://docs.microsoft.com/en-us/quantum/?view=qsharp-preview) for one month and I've found just now the two fantastic compilations of resources in https://qsharp.community/ and https://github.com/ebraminio/awesome-qsharp/ by reading issue #466 instead of from the main site. 

Most new users will start using and learning Q# through the material presented in the main site, but there is not a complete compilation of learning resources on the main site like the ones cited above (or even an _easy to find_ link to them).

There's the section "For more information", but it seems more oriented to provide useful references for advanced topics of Quantum Computing rather than learning material for Q#.

I wrote a small subsection [Learning materials](https://review.docs.microsoft.com/es-es/quantum/manual/?view=qsharp-preview&branch=qmanual#learning-materials) at the beginning of Q# Manual, but still is incomplete and it just will contribute to create more sparsity by adding a new different compilation in another random place.

I think we should create a section (or maybe a subsection on Getting started or Q# manual (?)) on the main site as an **official and structured compilation of learning resources**, explaining what the resources are for and how to use them depending on the level of expertise of the reader. This will help the reader to have a fixed point of reference for obtaining material. It will also help us by needing to keep up to date one single compilation that we can refer to in other sections, blogs... instead of having to update manually each compilation every time a new resource comes out.

Please, tell me what you think @cgranade, @bettinaheim, @bromeg. As I'm learning Q# from almost zero I could take care of and improve it as I learn and follow the different tutorials.

**Comment by crazy4pi314** [comment]
I am glad that https://qsharp.community/ is helpful! We are always looking for help collecting and maintaining resources, as well as blog posts about learning Q# and tools in that ecosystem.

**Comment by cgranade** [comment]
I think that's a great idea, and one that fits nicely in with how Microsoft docs tend to list resources more generally. For instance, Azure Functions provides a number of such resources in a separate TOC section at the bottom:

![image](https://user-images.githubusercontent.com/31516/64457028-71913100-d0a6-11e9-8d25-bc9742642b33.png)

Tagging @natke for further discussion as well.
