### ISSUE TITLE
Issue in an external link

### ISSUE THREAD

**Issue by Nathire** [MicrosoftDocs/quantum-docs-pr#488]
There is a problem for the link in the "File Structure" section. Can you fix it? Thank you ^^
Another thing, is it possible to be in contact with a Q# developer? Because I need help to do something in relation with Q# in Visual Studio. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 481eac22-8023-4ff2-d349-a3f42597d3bc
* Version Independent ID: 564ca910-6a5a-9885-1fba-0f9a9c250382
* Content: [The Q# Programming Language](https://docs.microsoft.com/en-us/quantum/language/?view=qsharp-preview#feedback)
* Content Source: [articles/language/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/language/index.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by cgranade** [comment]
Thanks for filing the bug, @Nathire! If you have a question about Q# and using the Quantum Development Kit more generally, [we recommend](https://github.com/microsoft/Quantum/blob/master/CONTRIBUTING.md#asking-questions) that the `q#` tag on [https://stackoverflow.com/questions/tagged/q%23](StackOverflow) and the [https://quantumcomputing.stackexchange.com/questions/tagged/q%23](Quantum Computing StackExchange) communities, or the [qsharp.community](https://qsharp.community) site. We're also happy to help with bugs and suggestions filed on [any of our various open source repositories](https://docs.microsoft.com/en-us/quantum/contributing/?view=qsharp-preview#where-do-contributions-go). Please let us know if there's something we can do to help, thanks for your interest in quantum development 💕!
