### ISSUE TITLE
Numerics package documentation

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs-pr#511]
I've seen that some operations (e.g. "Carry") are included in the Microsoft.Quantum.Arithmetic namespace by default, whilst there are some (e.g. "AddI") that need the Microsoft.Quantum.Numerics package installed. 

It would be helpful if this could be refenced somewhere in the documentation, for example in the summary of [Microsoft.Quantum.Arithmetic](https://docs.microsoft.com/en-gb/qsharp/api/qsharp/microsoft.quantum.arithmetic?view=qsharp-preview), that some of the operations in Arithmetic require the Numerics package with a link to the [installation](https://docs.microsoft.com/en-gb/quantum/libraries/numerics/installation?view=qsharp-preview).

Thanks,
Frances

**Comment by cgranade** [comment]
That's a good point, @frtibble, thanks for raising the issue. At the moment, we don't have a great way to document which package contributes a given operation or function; especially for those namespaces like `Microsoft.Quantum.Arithmetic`, `Microsoft.Quantum.Math`, and `Microsoft.Quantum.Convert` that are split across packages, it would be good if we could document that similarly to how C# API docs list which assembly contributes a given type. I like the idea of providing better links from namespace descriptions in the meantime, though, as a workaround.

+@bromeg, @natke, and @v-stgr for discussion.

**Comment by frtibble** [comment]
Yes, I agree - your first suggestion would be the clearest, I think, and it'd make the most sense given that's how it's documented in C#. Thanks for considering my suggestion too.

**Comment by natke** [comment]
It sounds like we need to document the dependencies between packages?

Is there a one to one correspondence between package and namespace, or not?

**Comment by cgranade** [comment]
There's not generally a one-to-one mapping between namespaces and packages, unfortunately. They are pretty correlated, but there's also namespaces like `Microsoft.Quantum.Math` and `Microsoft.Quantum.Diagnostics` that get split across packages for various technical reasons. For the most part, if a user uses the new SDK package, then they should be OK to use everything in the references except for domain-specific functionality brought in from Microsoft.Quantum.Chemistry.*, Microsoft.Quantum.Numerics, Microsoft.Quantum.Research, and Microsoft.Quantum.MachineLearning.
