### ISSUE TITLE
Update instructions for VS code extension

### ISSUE THREAD

**Issue by natke** [MicrosoftDocs/quantum-docs-pr#512]
As it stands, creating a new Q# project fails if you install the VS code extension, using these instructions: https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-vscode&view=qsharp-preview

The templates need to be installed as a separate step:

From within VS you can create a new project with the standard GUI option (right click solution, new project etc). If you want to create a project from the command line you have to install the project templates, which are a separate nuget package: https://www.nuget.org/packages/Microsoft.Quantum.ProjectTemplates/0.9.1908.2906

**Comment by cgranade** [comment]
Thanks for filing this, I agree we should be more clear about the requirement that project templates are installed before hand. From the command line (whether standalone or the integrated terminal within VS Code), `dotnet new -i Microsoft.Quantum.ProjectTemplates` should do it. For VS Code in particular, the "Q#: Install project templates..." command from the Command Palette can also be used.

**Comment by natke** [comment]
This is fixed by #533
