### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by christopherkang** [MicrosoftDocs/quantum-docs-pr#517]
Link at the bottom of the page in "Multiple chemical representations defined using the Broombridge schema are provided here." is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591eac7c-7f73-6759-028b-c8a1bbb5f151
* Version Independent ID: 89a7fb7b-6a8c-f0fd-a3a4-59d54f24fd8c
* Content: [Broombridge - Quantum Chemistry Schema](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/schema/broombridge?view=qsharp-preview)
* Content Source: [articles/libraries/chemistry/schema/broombridge.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/schema/broombridge.md)
* Product: **quantum**
* GitHub Login: @MartinRo
* Microsoft Alias: **martinro@microsoft.com**

**Comment by tcNickolas** [comment]
Fixed in PR #538 - thank you for bringing this to our attention!
