### ISSUE TITLE
First instruction for Update is confusing

### ISSUE THREAD

**Issue by bromeg** [MicrosoftDocs/quantum-docs-pr#521]
1. Consult Nuget.org for the PackageReference number, "0.n.xxxx.yyy" for the Microsoft Quantum Development Kit package.
-&gt; This is not a helpful instruction for folks unfamiliar with Nuget. We shouldn't expect any deep knowledge about Nuget, and we should rephrase "0.n.xxxx.yyy" to instead say something around picking up the latest version.
2. Projects need to be upgraded in order. If you have a solution with multiple projects, update each project in the order they are referenced.
-&gt; Can we include some detail here on how a user can check in which order their projects are referenced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2cb8a12-0fe8-6b27-c3a6-c7d4b9a089f8
* Version Independent ID: b1ddff8c-781e-6b1b-604a-01bb5207f897
* Content: [Getting Started with C# and Q#](https://docs.microsoft.com/en-us/quantum/install-guide/csharp?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/csharp.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csharp.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **anpaz@microsoft.com**

**Comment by natke** [comment]
@bromeg, can you please check to see whether this issue is resolved by the recent addition of a separate update guide? https://docs.microsoft.com/en-us/quantum/install-guide/update?view=qsharp-preview

**Comment by bromeg** [comment]
Solved by improvements to update guide.
