### ISSUE TITLE
Product symbol

### ISSUE THREAD

**Issue by rdisipio** [MicrosoftDocs/quantum-docs-pr#532]
It may be trivial given the context, but what does the $\otimes$ operator actually correspond to? Kronecker product?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4f0bcf-e335-8173-6761-d3440f84db82
* Version Independent ID: 98d49390-a026-46ce-2886-19969fe24224
* Content: [Jordan-Wigner Representation - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/concepts/jordan-wigner?view=qsharp-preview#feedback)
* Content Source: [articles/libraries/chemistry/concepts/jordan-wigner.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/concepts/jordan-wigner.md)
* Product: **quantum**
* GitHub Login: @nathanwiebe2
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by tcNickolas** [comment]
Yes, ⊗ is Kronecker product (usually referred to as tensor product in quantum computing). This operation is introduced and discussed in greater detail [earlier in the documentation](https://docs.microsoft.com/quantum/concepts/multiple-qubits).
