### ISSUE TITLE
The "Develop with Python" steps don't work on Mac (10.14.6)

### ISSUE THREAD

**Issue by davidfgarcia** [MicrosoftDocs/quantum-docs-pr#537]
When I run this step:

dotnet iqsharp install

I get this error:

It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      2.1.12 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      3.0.0-preview9.19424.4 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

I have the latest version of .NET Core and the latest version of Python installed. OS X version is 10.14.6.

Thanks a lot,

-david

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by davidfgarcia** [comment]
I got around this issue by manually installing release 2.2.7 from https://dotnet.microsoft.com/download/dotnet-core

Is it not working with the latest version? The requirement in the steps is .NET Core SDK 2.1 **or later**...

Thanks a lot!

**Comment by natke** [comment]
Hi @davidfgarcia, I'm not currently able to reproduce this issue.

Can you please run the following command to check the version of the iqsharp global tool that you have installed, to allow us to investigate further:

```
dotnet iqsharp --version
```

**Comment by davidfgarcia** [comment]
Sure; here's the output:

$ dotnet iqsharp --version
iqsharp: 0.9.1909.3002
Jupyter Core: 1.1.18837.0

One thing I didn't mention is that my default python settings are for python 2.7; for python 3 I have to explicitly specify it in my commands (e.g. python3, pip3, etc).

Just in case this could be making a difference.

Thanks a lot,

-david

**Comment by natke** [comment]
@davidfgarcia,

I don't think the python version should not make a difference at this point in the installation.

Can you please install .NET core 3 again and run the following commands, and paste the output in your response:

```
dotnet --list-sdks
dotnet iqsharp install
dotnet iqsharp --version
```

Thank you!

**Comment by davidfgarcia** [comment]
@natke - Here it is:

David’s MacBook Pro:~ dafigu$ dotnet --list-sdks
2.1.701 [/usr/local/share/dotnet/sdk]
2.1.802 [/usr/local/share/dotnet/sdk]
2.2.402 [/usr/local/share/dotnet/sdk]
3.0.100-preview9-014004 [/usr/local/share/dotnet/sdk]
3.0.100 [/usr/local/share/dotnet/sdk]
David’s MacBook Pro:~ dafigu$ dotnet iqsharp install
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/iqsharp
[InstallKernelSpec] Installed kernelspec iqsharp in /usr/local/share/jupyter/kernels/iqsharp
David’s MacBook Pro:~ dafigu$ dotnet iqsharp --version
iqsharp: 0.9.1909.3002
Jupyter Core: 1.1.18837.0
David’s MacBook Pro:~ dafigu$

**Comment by natke** [comment]
So that looked like it worked. Does that unblock you? We'll investigate your original issue from with a fresh install. (Just verifying that you were doing a fresh install? i.e. you had no previous versions of iqsharp installed?)

**Comment by davidfgarcia** [comment]
Sure, I got unblocked after installing release 2.2.7.

But yes, I think it would be worth for you guys to try the docs steps from a fresh install, just in case this is a widespread issue and not just something related to my specific machine config.

Thanks a lot for following up!

**Comment by natke** [comment]
Notes from dev team: install does not work when .NET core 3.0 SDK *only* is installed.

**Comment by natke** [comment]
I have followed up with the dev team, and we are taking steps to ameliorate this issue. In the mean time, I will add some notes to the installation docs to make people aware of this. I will close this issue now. Please let us know if you have any further problems. Thanks for using the QDK!

**Comment by davidfgarcia** [comment]
Sounds good, thanks!
