### ISSUE TITLE
Microsoft.Quantum.Primitive namespace still used in trace simulator docs`

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#543]
With 0.6, the Microsoft.Quantum.Primitive namespace was deprecated in favor of Microsoft.Quantum.Intrinsic, but the trace simulator page still uses the old name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7246f0e0-b02d-f44f-5236-bd114b52f583
* Version Independent ID: a4e754aa-b88e-aa4b-1524-65cd7b0f4a6f
* Content: [Quantum computer trace simulator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/machines/qc-trace-simulator/?view=qsharp-preview#providing-the-probability-of-measurement-outcomes)
* Content Source: [articles/machines/qc-trace-simulator/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/machines/qc-trace-simulator/index.md)
* Product: **quantum**
* GitHub Login: @vadym-kl
* Microsoft Alias: **vadym@microsoft.com**

**Comment by gillenhaalb** [comment]
Found that a few other pages linked to the deprecated operations too, fixed in PR #659

**Comment by gillenhaalb** [comment]
Fixed by #659
