### ISSUE TITLE
Jupyter kernel iqsharp wants old .NET version 2 

### ISSUE THREAD

**Issue by stanescuUW** [MicrosoftDocs/quantum-docs-pr#548]
Current version of .NET is 3; after installing this and trying to install the Jupyter kernel, got an error message. The kernel won't install unless it finds .NET 2; it did install after installing the older .NET version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/index?view=qsharp-preview)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by cgranade** [comment]
Thanks for the report! We're currently tracking this at microsoft/iqsharp#42, so I'm closing this issue as a duplicate; please feel free to follow up at the original issue. Thanks!

**Comment by cgranade** [comment]
I apologize for forgetting to mention earlier, but as we actively work to resolve this problem, you can work around the issue in the meantime by installing the [.NET Core SDK, version 2.2](https://dotnet.microsoft.com/download/dotnet-core/2.2) rather than version 3.0. Thanks for your patience!

**Comment by stanescuUW** [comment]
Yes, I did that already. Thanks a lot Chris for your help and for caring so much!
