### ISSUE TITLE
Set (initial, q0);

### ISSUE THREAD

**Issue by tonio-lora** [MicrosoftDocs/quantum-docs-pr#552]
I get an error on this Q# line related to Set: "No identifier with that name exists". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e984fdb6-63e6-92ac-f794-8a15a5092559
* Version Independent ID: bcd9a2e2-0b07-514e-5b43-8b3e092669ce
* Content: [Write a quantum program - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstart?view=qsharp-preview&tabs=tabid-vscode)
* Content Source: [articles/quickstart.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstart.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by tonio-lora** [comment]
Sorry, forgot to add the Set operation.

**Comment by alan-geller** [comment]
The `set` statement is used to change the value of an existing mutable variable. That is, any variable on the left-hand side of a `set` statement must have previously been defined in a `mutable` statement.

If this doesn't address your problem, would you be able to provide a longer code snippet?

Thanks!!

**Comment by alan-geller** [comment]
Would you be able to provide a larger Q# code snippet? It should look like the 4th or 5th box in step 6; seeing how it's different will help me diagnose this.

Thanks!!

**Comment by bromeg** [comment]
Thank you for the feedback! We're working on making the quickstart less confusing. We will circle back when the new quickstart is out, please let us know if you run into the same issue.

Thanks!
