### ISSUE TITLE
Typo in an example code for "Update-and-Reassign Statement"

### ISSUE THREAD

**Issue by tanaka-takayoshi** [MicrosoftDocs/quantum-docs-pr#601]
[Enter feedback here]
There is a typo in an example code in [Update-and-Reassign Statement](https://docs.microsoft.com/en-us/quantum/language/statements?view=qsharp-preview#update-and-reassign-statement).

```
newtype Complex = (Re : Double, Im : Double);

function AddAll (reals : Double[], ims : Double[]) : Complex[] {
    mutable res = Complex(0.,0.);

    for (r in reals) {
        set res w/= Re <- res::Re + r; // update-and-reassign statement
    }
    for (i in ims) {
        set res w/= Im <- res::Im + i; // update-and-reassign statement
    }
    return res;
}
```

The return type of `AddAll` method should be `Complex` rather than `Complex[]`.

```
newtype Complex = (Re : Double, Im : Double);

function AddAll (reals : Double[], ims : Double[]) : Complex {
    mutable res = Complex(0.,0.);

    for (r in reals) {
        set res w/= Re <- res::Re + r; // update-and-reassign statement
    }
    for (i in ims) {
        set res w/= Im <- res::Im + i; // update-and-reassign statement
    }
    return res;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a89111-4a06-95d4-b6a5-304f0a6df7af
* Version Independent ID: 450e9625-f516-b331-cb07-3b1f7030e663
* Content: [Q# statements - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/language/statements?view=qsharp-preview#update-and-reassign-statement)
* Content Source: [articles/language/statements.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/language/statements.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by gillenhaalb** [comment]
@tanaka-takayoshi Good catch, thanks for the heads up! Adding the fix to a PR now.
