### ISSUE TITLE
Form for providing feedback on docs page always fails

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#628]
This is a pretty minor one, but when I go to add comments/feedback in the in-page issue form (love it btw ♥) it usually fails the first time and then I have to click the link in the red bar (as shown in the photo) to submit issue. It often gets the right context for the issue, but can fail to copy over what I typed in in the box on the docs page so I have to re-create it there. 

![image](https://user-images.githubusercontent.com/6486256/69921131-816da680-1444-11ea-9389-eaeab2f78cf0.png)

**Comment by natke** [comment]
Thank you for reporting this issue @crazy4pi314. Can you please link to the page that you are having trouble reporting feedback on?

**Comment by crazy4pi314** [comment]
It happens on every page I have tried in the last few weeks (~3-4 pages), the screenshot from above was on [microsoft.quantum.canon.splitarray](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.canon.splitarray?view=qsharp-preview). I know it also happened when I filed this issue too: https://github.com/microsoft/Quantum/issues/271#issue-527610486 
I don't remember the other pages off the top of my head. I can reproduce it every time by just trying to use the form on the page, this screen shot is from chrome on mobile, on the page for [CNOT](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.cnot?view=qsharp-preview).
![Screenshot_20191202-105139](https://user-images.githubusercontent.com/6486256/69986248-db787580-14f1-11ea-92b0-9c983dec74a0.png)

**Comment by natke** [comment]
Thank you @crazy4pi314. We have reproduced the issue in the reference documentation pages. (The problem does not occur in the conceptual doc pages)

**Comment by natke** [comment]
@anpaz-msft, the current target for issues in the API docs is the github.com/microsoft/quantum repo. Is this where we want API docs issues to go? If so, can you check which app integrations are installed on that repo please? (I don't have access)

**Comment by KittyYeungQ** [comment]
@anpaz-msft checking in if the questions from @natke are clarified.
