### ISSUE TITLE
Confusing line about comparing value of user types.

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/quantum-docs-pr#637]
The line is “Values of user-defined types may not be compared, only their values can be compared.” It’s self contradictory, perhaps “only their unwrapped values can be compared” or similar change would resolve?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0386e920-3c2b-81a6-f32c-12653d2b0321
* Version Independent ID: 854cd620-b8ec-270b-8d55-34952a234016
* Content: [Expressions - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/language/expressions?view=qsharp-preview#feedback)
* Content Source: [articles/language/expressions.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/language/expressions.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by gillenhaalb** [comment]
@jwittner good catch! Thanks for the heads up, I'm adding the fix/clarification to a PR now.
