### ISSUE TITLE
Deutsch–Jozsa algorithm link

### ISSUE THREAD

**Issue by traesw** [MicrosoftDocs/quantum-docs-pr#639]
Deutsch–Jozsa algorithm link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c855df6d-d8b4-9197-70d2-e26003484290
* Version Independent ID: 141ee72e-d0e9-7efa-b94a-6bddeefee27a
* Content: [Introduction to the Quantum Katas - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/intro-to-katas?view=qsharp-preview#feedback)
* Content Source: [articles/intro-to-katas.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/intro-to-katas.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by tcNickolas** [comment]
Thank you for reporting this!
