### ISSUE TITLE
Error is reported without link to GitHub issue in Sample SDK

### ISSUE THREAD

**Issue by jwittner** [MicrosoftDocs/quantum-docs-pr#641]
The line is "do not select Rebuild Solution, as rebuilding will initially fail". I found the bug below, not sure if it's the same.

https://github.com/microsoft/Quantum/issues/11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3597a337-2064-d3c3-2284-a36d2431c38c
* Version Independent ID: 350fe86e-8e34-4b91-eda6-1ce6ea6aee9f
* Content: [Learn how to update the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/update?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/update.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/update.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by gillenhaalb** [comment]
Clarifying the instructions in a pending PR, thanks!
