### ISSUE TITLE
Dotnet command line installation problem

### ISSUE THREAD

**Issue by JulesMhz** [MicrosoftDocs/quantum-docs-pr#642]
Hello,
I have installed Miscrosoft .Net Core SDK 3.1.100 (x64), and after the reboot I tried to install the Quantum project templates for .NET with dotnet command line, so I run the command "dotnet new -i Microsoft.Quantum.ProjectTemplates". I receive the error message : 

error NU1100: Impossible de résoudre 'Microsoft.Quantum.ProjectTemplates ' pour '.NETCoreApp,Version=v1.0'. (In english : impossible to solve 'Microsoft.Quantum.ProjectTemplates ' for...

Have you got an idea how to fix it ?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/index?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by cgranade** [comment]
Thanks for your report! It looks for some reason like the project template installation attempted to use .NET Core SDK 1.0 instead of the 3.1.100 version you installed. Would you be willing to paste the output of `dotnet --info` here to help diagnose? Thanks!

**Comment by JulesMhz** [comment]
Thank you for your repply, here is the output of the info command line : 

SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.100
 Commit:    cd82f021f4

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
