### ISSUE TITLE
Errors on landing page

### ISSUE THREAD

**Issue by bromeg** [MicrosoftDocs/quantum-docs-pr#644]
Errors on the landing page: https://docs.microsoft.com/en-us/quantum/?view=qsharp-preview

Update title & sentence at top of the landing page:
o	"Microsoft Quantum Documentation" -> "Quantum Development Kit" 
o	Quantum Developer Kit -> Quantum Development Kit
o	language for quantum algorithms -> "language for programming quantum algorithms"

**Comment by gillenhaalb** [comment]
Fixed by PR #645, closing
