### ISSUE TITLE
Figures don't work on dark page mode

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#648]
When using a dark theme for the docs pages, the figure labels are mostly illegible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?view=qsharp-preview)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment]
True! Good catch! Probably it might be better to use plain images with a white background rather than transparent .svg's. I'll change it. Thanks!

**Comment by cgranade** [comment]
Closing, as #657 should resolve this issue. Thanks for the report, @crazy4pi314!
