### ISSUE TITLE
The exaplnation is strightforward, very good tutorial

### ISSUE THREAD

**Issue by francescosisini** [MicrosoftDocs/quantum-docs-pr#649]
Quantum superposition principle is explained without get the reader confused

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?view=qsharp-preview#feedback)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment]
Thank you very much for your feedback! We are working to expand a bit the tutorial to also show how to create random integers using an external host program. Stay tuned!

**Comment by KittyYeungQ** [comment]
Thank you for the feedback.
