### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#651]
In the Correlations between qubtis section, the link in "See Q# library reference for Pauli measurements" is broken. I think it should link to https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.measurement.measurepaulis?view=qsharp-preview . 
It was likely broken when the namespace changed :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fa8b49-db57-3ecb-0f9b-9e32feee3ebc
* Version Independent ID: bc76d802-3855-b0ce-4131-f44852e7d419
* Content: [Pauli Measurements - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/pauli-measurements.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/pauli-measurements.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by jks-liu** [comment]
When will this PR be updated to Microsoft site?

**Comment by cgranade** [comment]
@jks-liu: Thanks for your question! We're tracking updating the live site at #656, you can watch our discussion there.
