### ISSUE TITLE
Probably alright if you already know this stuff.

### ISSUE THREAD

**Issue by trippalamb** [MicrosoftDocs/quantum-docs-pr#655]
Probably good if you already know what everything means. There are several keywords and operations that exist on the page that were not in the previous quickstarts that have no indication of what they might be or mean. The comments are not excellent either. I understand that explaining the keywords and procedures might be to much for this tutorial but there is no link to the documentation either. For example "Z()", "Unit is ADj + Ctl", and "Controlled", but there are many more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70204502-115d-e309-2af9-9b1ee504aabd
* Version Independent ID: 4df8db39-ccc1-d145-96b5-926df47408b0
* Content: [Run Grover's search algorithm in Q# - Quantum Development Kit - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/search?view=qsharp-preview&tabs=tabid-vs2019#feedback)
* Content Source: [articles/quickstarts/search.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/search.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad@microsoft.com**

**Comment by geduardo** [comment]
Thank you very much for the feedback! It is true that Grover's tutorial maybe is a bit advanced for a quick start, but we wanted to showcase a complete code with a popular quantum computing algorithm. If you want to learn more about functors Adj and Ctl take a look here: https://docs.microsoft.com/en-us/quantum/language/type-model?view=qsharp-preview#functors

We plan to create more tutorials to provide a softer and continuous introduction to the QDK. Stay tuned!

**Comment by KittyYeungQ** [comment]
#663 will address this.

**Comment by geduardo** [comment]
I think this is solved with the new user guide.
