### ISSUE TITLE
Add reference for IQ# magic commands

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#658]
At the moment, we don't really have a reference for what magic commands exist in IQ#, but the list has gotten longer as we go forward with that project:
- `%config` (coming with microsoft/iqsharp#81): Sets or gets configuration preferences.
- `%estimate`: Runs a given function or operation on the QuantumSimulator target machine
- `%package`: Provides the ability to load a Nuget package.
- `%simulate`: Runs a given function or operation on the QuantumSimulator target machine
- `%toffoli`: Runs a given function or operation on the ToffoliSimulator simulator target machine
- `%who`: Returns a list of currently defined operations and functions
- `%workspace`: Provides actions related to the current workspace

The Microsoft.Quantum.Katas package adds `%kata` and `%check_kata` as well, which aren't documented anywhere at the moment.

**Comment by gillenhaalb** [comment]
@cgranade I haven't dabbled with the Q# Jupyter Notebooks much, but can easily imagine this being a huge frustration to those trying to use it. Are you thinking a page/section to tuck in the "Reference" tab?

![image](https://user-images.githubusercontent.com/47889725/72681336-c5833c00-3ac2-11ea-8156-ef1eb1841ba0.png)

**Comment by cgranade** [comment]
@gillenhaalb: My thought was that the Reference section you highlighted is mainly for the various API references, but perhaps we could have a reference somewhere in a user manual?

**Comment by cgranade** [comment]
@gillenhaalb: My thought was that the Reference section you highlighted is mainly for the various API references, but perhaps we could have a reference somewhere in a user manual?

**Comment by gillenhaalb** [comment]
Will make a command quick reference section in the Q# manual (#663)
