### ISSUE TITLE
Please improve discoverability of information on adjoint and controlled

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#660]
I've observed multiple times that information on adjoint and controlled versions of the operations is shared on multiple pages and hard for the reader to discover (for example, searching for `adj` or `ctl` doesn't show any relevant articles - if we had a separate article called "Adjoint and controlled", things would be so much easier!). You can see https://github.com/microsoft/QuantumKatas/issues/274 for a more detailed report by a reader.

**Comment by geduardo** [comment]
This should be addressed in #663!
