### ISSUE TITLE
Two minor corrections

### ISSUE THREAD

**Issue by ryporter** [MicrosoftDocs/quantum-docs-pr#661]
In the definition of the generic Map, the return type should be 'Output[] instead of 'Output.  

Also, for all of the declared types of the argument "fn" (e.g., 'Input -&gt; 'Output in the same generic Map), parentheses are need (at least in the version of the compiler I'm using).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc48da7-4d2a-4df9-c361-54299580723c
* Version Independent ID: d23f113c-3b7f-3a53-1753-580938437041
* Content: [Q# techniques - going further - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/techniques/going-further?view=qsharp-preview#feedback)
* Content Source: [articles/techniques/going-further.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/techniques/going-further.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by gillenhaalb** [comment]
@ryporter Good catch, thanks for letting us know! Fixing in a PR now
