### ISSUE TITLE
PrepareTrialState API documentation differs from the example

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#664]
"Contributing documentation" page has a nice detailed example of API documentation for PrepareTrialState operation, which has a [page at API documentation as well](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.chemistry.jordanwigner.preparetrialstate). However, the API documentation at that page is missing (other than the operation signature). 

It would be very helpful if the documentation at that page matched the example, so that the reader could see the comments that are the source for API documentation together with the generated documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058790a7-072d-b185-97e1-1c9290809f88
* Version Independent ID: 4712e099-0e7c-604f-0986-52c8ad04a684
* Content: [Contributing documentation - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/contributing/docs?view=qsharp-preview)
* Content Source: [articles/contributing/docs.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/contributing/docs.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by geduardo** [comment]
Oh, that's bad. However, taking a quick look I think they refer to different operations that unfortunately happen to have the same name. 
If I understood it correctly, the Jordan Wigner PrepareTrialState is an operation for the chemistry library but PrepareTrialState in the documentation tutorial is just an example that @cgranade invented just to show how to create API references. 
I see two solutions: 
- To change the name of the example to avoid confusion.
- To change the example to a real operation so the final generated documentation can be seen by the reader.

**Comment by tcNickolas** [comment]
A real example would be better. I don't think we have any shortage of real examples :-)
