### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by ulitoo** [MicrosoftDocs/quantum-docs-pr#666]
The Q# standard libraries provide several different functions for representing facts, including:

- Fact
- EqualityWithinToleranceFact
**- <xref:microsoft.quantum.diagnostics.nearequalityfact>**
- EqualityFactI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2cf12c5-1eb3-70e7-8634-010dce47665b
* Version Independent ID: 81b94e71-0b24-b23c-5eff-883b50fde826
* Content: [Q# standard libraries - diagnostics - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/diagnostics?view=qsharp-preview)
* Content Source: [articles/libraries/standard/diagnostics.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/diagnostics.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad@microsoft.com**

**Comment by geduardo** [comment]
Good catch, thank you!

**Comment by cgranade** [comment]
Closing, as this has been fixed with #667.
