### ISSUE TITLE
Including link to source code on GitHub in API reference

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#668]
Could it be possible to show a link to the source code on GitHub of each operation in the API reference? 
This would make it easier to contribute since now to edit or enhance the API documentation you have first to find the Quantum Libraries repo and then to find the file in which each operation is defined. Potential contributors will likely get lost in the process as it is now.

**Comment by cgranade** [comment]
@geduardo: I agree that would be quite nice. There's a number of different moving pieces to that, though:
- New metadata would have to be added to the Q# project file format to track that.
- The compiler would need to be augmented to read that metadata and pass it along to the documentation generation tool.
- The documentation generation tool would need to be updated to pass that information along to the generated documentation YAML files.
- The documentation schema would need to be updated to store this new information.
- The docs.microsoft.com template would need to be updated to expose this new information.

For the first three, we'd need input from @bettinaheim and her team to assess how reasonable that is; I'd suggest opening a feature request on the qsharp-compiler repo to track that. Unfortunately, the latter two are not under the team's direct control (see, for example microsoft/qsharp-compiler#113), such that we'd need some input from @KittyYeungQ and @bromeg about how to best proceed there.

**Comment by tcNickolas** [comment]
For the last two items, we could get away with just generating a standardized remark "You can find the source code for this item at (link)".

**Comment by cgranade** [comment]
> For the last two items, we could get away with just generating a standardized remark "You can find the source code for this item at (link)".

We could, yes, but that we have as many other issues with the current Q# API documentation schema suggests to me that it may be worth looking into how to update the schema to support our current API documentation needs.

**Comment by KittyYeungQ** [comment]
Perhaps @cjgronlund could provide some input on the last two points about docs schema and template?
