### ISSUE TITLE
problem for the matemathical examples #2

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/quantum-docs-pr#669]
@Johnabarreto commented 15 hours ago — with docs.microsoft.com

In the mathematical examples no working fine, show this information: \begin{align} & \begin{bmatrix} 1 \ 0 \end{bmatrix} ^ {\otimes 1} = \begin{bmatrix} 1

In English working fine!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by ticianaciminari** [comment]
Hi Team, could you please use the non-loc feature for these vectors and matrices? In English looks fine but in targets they appear as plain text.

![image](https://user-images.githubusercontent.com/43826292/73298846-daf81480-41ec-11ea-9393-565a0cf6ce7e.png)

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by ticianaciminari** [comment]
@QuantumWriter

**Comment by ticianaciminari** [comment]
#https://github.com/MicrosoftDocs/quantum-docs-pr.es-ES/issues/2

**Comment by KittyYeungQ** [comment]
The matrices also don't show up in English on the [GitHub page](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md) here. It shows in the [docs page](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices?view=qsharp-preview#feedback) though. @natke Is this something you may be able to help?

**Comment by cgranade** [comment]
Math rendering is done by the MathJax client-side package included into docs.microsoft.com by the DocFX toolchain. Given that process, it is expected and correct that mathematical notation does not render in GitHub previews, as said previews don't support injecting MathJax.

**Comment by gillenhaalb** [comment]
> Hi Team, could you please use the non-loc feature for these vectors and matrices? In English they look fine but in targets they appear as plain text.
> 
> ![image](https://user-images.githubusercontent.com/43826292/73298846-daf81480-41ec-11ea-9393-565a0cf6ce7e.png)
> 
> Kind regards,
> 
> Microsoft DOCS Global Experience Team

@cgranade is this rendering-lost-in-translation something we can take care of in the macros of the English repo?

**Comment by cgranade** [comment]
@gillenhaalb: Comparing the raw Markdown, the `es-ES` version of the page has the following DFM source:

```
\begin{align} M \otimes N & = \begin{bmatrix} m_{11} ~ ~ \cdots ~ ~ m_ {1N} \\\\ \ddots\\\\ m_ {M1} ~ ~ \cdots ~ ~ m_ {MN} \end{bmatrix} \otimes \begin{bmatrix} n_{11} ~ ~ \cdots ~ ~ n_ {1T}\\\\ \ddots @no__ t_8_ \\ n_ {P1} ~ ~ \cdots ~ ~ n_ {pq} \end{bmatrix}\\\\ & = \begin{bmatrix} m_{11} \begin{bmatrix} n_{11} ~ ~ \cdots ~ ~ n_ {1P}\\\\ \ddots\\\\ n_ {P1} ~ ~ \cdots ~ ~ n_ {pq} \end{bmatrix} ~ ~ \cdots ~ ~ m_ {1N} \begin{bmatrix} n_{11} ~ ~ \cdots ~ ~ n_ {1T}\\\\ \ddots\\\\ n_ {P1} ~ ~ \cdots ~ ~ n_ {pq} \end{bmatrix}\\\\ \ddots\\\\ m_ {M1} \begin{bmatrix} n_{11} ~ ~ \ cdots ~ ~ n_ {1T}\\\\ \ddots\\\\ n_ {P1} ~ ~ \cdots ~ ~ n_ {pq} \end{bmatrix} ~ ~ \cdots ~ ~ m_ {MN} \begin{bmatrix} n_{11} ~ ~ \cdots ~ ~ n_ {1P}\\\\ \ddots\\\\ n_ {P1} ~ ~ \cdots ~ ~ n_ {pq} \end {bmatrix} \end{bmatrix}.
\end{align}
```

Meanwhile, the `en-US` DFM looks like the following:
```
\begin{align}
	M \otimes N &=
	\begin{bmatrix}
		M_{11} ~~ \cdots ~~ M_{1n} \\\\
		\ddots\\\\
		M_{m1}  ~~ \cdots ~~ M_{mn}
	\end{bmatrix}
	\otimes
	\begin{bmatrix}
		N_{11}  ~~ \cdots ~~ N_{1q}\\\\
		\ddots\\\\
		N_{p1} ~~ \cdots ~~ N_{pq}
	\end{bmatrix}\\\\
	&=
	\begin{bmatrix}
		M_{11} \begin{bmatrix} N_{11}  ~~ \cdots ~~ N_{1q}\\\\ \ddots\\\\ N_{p1} ~~ \cdots ~~ N_{pq} \end{bmatrix}~~ \cdots ~~ 
		M_{1n} \begin{bmatrix} N_{11}  ~~ \cdots ~~ N_{1q}\\\\ \ddots\\\\ N_{p1} ~~ \cdots ~~ N_{pq} \end{bmatrix}\\\\
		\ddots\\\\
		M_{m1} \begin{bmatrix} N_{11}  ~~ \cdots ~~ N_{1q}\\\\ \ddots\\\\ N_{p1} ~~ \cdots ~~ N_{pq} \end{bmatrix}~~ \cdots ~~ 
		M_{mn} \begin{bmatrix} N_{11}  ~~ \cdots ~~ N_{1q}\\\\ \ddots\\\\ N_{p1} ~~ \cdots ~~ N_{pq} \end{bmatrix}
	\end{bmatrix}.
\end{align}
```

The whitespace changes shouldn't be significant, but changing `~~` to `~ ~` may be?

**Comment by gillenhaalb** [comment]
@cgranade Ah, yes, that makes sense. A few other places where spaces found there way in too, like `&=` becoming `& =`.

**Comment by sutteri** [comment]
this problem is occuring at every webpage wherever there is the mathematical expressions!!
how to fix it  ??

**Comment by KittyYeungQ** [comment]
Hi @sutteri thank you for reaching out. We just noticed the problem as well. The rendering stopped working as we noticed yesterday. We are trying to find the root cause.

**Comment by sutteri** [comment]
thanks for your response ..yes the rendering has stopped... i was trying to
learn quantum computing and this happened last night !!
