### ISSUE TITLE
Big Endian explanation clarification

### ISSUE THREAD

**Issue by ulitoo** [MicrosoftDocs/quantum-docs-pr#673]
In Quantum Fourier Transform section:

Where it says:
"The input and output are assumed to be encoded in big endian encoding (lowest bit/qubit is on the left, same as ket notation)."

could say:
"The input and output are assumed to be encoded in big endian encoding (least significant bit/qubit is on the right, same as ket notation)."

This might be clearer to the reader

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4d51b3a-7210-a5c6-135b-c176e6795e0a
* Version Independent ID: 1f2bef66-bc42-45ca-3476-6fea1d5569bf
* Content: [Q# standard libraries - algorithms - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/algorithms?view=qsharp-preview)
* Content Source: [articles/libraries/standard/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/algorithms.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

**Comment by gillenhaalb** [comment]
Thanks for your feedback! I absolutely agree, the wording there was quite unclear. I've just added clarification in a PR, so it should be live in the coming days 👍
