### ISSUE TITLE
 quantum-docs-pr/articles/quickstarts/search.md 

### ISSUE THREAD

**Issue by andrewenoble** [MicrosoftDocs/quantum-docs-pr#681]
Looks like the code for Operations.qs got cut off on the website:  https://docs.microsoft.com/en-us/quantum/quickstarts/search?view=qsharp-preview&tabs=tabid-vs2019  

The complete code appears to be here:  https://github.com/microsoft/Quantum/blob/master/samples/algorithms/simple-grover/SimpleGrover.qs

**Comment by geduardo** [comment]
Thank you very much! I cannot reproduce your error, everything appears ok to me in the browsers I tried (Chrome, Edge and Edge Chromium). 
Can you confirm that you're still getting the code cut off? Just discard a temporary synchronisation error between repos.

**Comment by andrewenoble** [comment]
I just tried again in Chrome, Firefox, and Safari.  Apologies if I'm missing something obvious.  I see the same Operations.qs snippet (after following the first link above) in all three browsers.  

[
<img width="637" alt="Grover_screenshot" src="https://user-images.githubusercontent.com/1040642/73750873-f9e63180-472b-11ea-9f29-fbe23f981251.png">
](url)

**Comment by geduardo** [comment]
Oh, I wasn't understanding you correctly, now I get what you mean, my bad. Yes, you're right. However, that cut apparently was made intentionally by looking at the .md code. But I don't get why, maybe it is a mistake on the ending line.
@cgranade, I think you were involvend in this tutorial. Is there any reason why the code is cut at line 27 to not show `NIterations`? If not I can make a quick PR to change the ending line.
