### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by leseixas** [MicrosoftDocs/quantum-docs-pr#686]
When I try to execute the example in my computer, I got the error message:

fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "v" exists.
Traceback (most recent call last):
  File "host.py", line 2, in &lt;module&gt;
    from Qrng import SampleQuantumRandomNumberGenerator # We import the 
ModuleNotFoundError: No module named 'Qrng'

When we write the command: from X import Y in the python host file, this means from "namespace X in Operation.qs"  import "operation Y". Right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?view=qsharp-preview&tabs=tabid-python#feedback)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by cgranade** [comment]
That error message seems to indicate that the Q# compilation step failed, such that no namespaces are made available. Thus, the `from Qrng import SampleQuantumRandomNumberGenerator` line fails as a result of the earlier error message `QS5022: No identifier with the name "v" exists.`. Did you modify the Q# code at all? The identifier `v` doesn't appear in the Qrng sources at https://github.com/microsoft/Quantum/blob/master/samples/getting-started/qrng/Qrng.qs, so I'm not sure where that might be coming from, sorry.

**Comment by leseixas** [comment]
No, I did not modified the Q# code. Just installed the dotnet and Q# in my computer, ran the HelloWorld program without problems, and tried to run this example.

**Comment by anpaz-msft** [comment]
It's unclear where that "v" is coming from, but there are a couple of bugs in the Python code of that page.

Considering the Q# code is:
```q#
namespace Quantum {
    open Microsoft.Quantum.Intrinsic;

    operation QuantumRandomNumberGenerator() : Result {
        using(qubit = Qubit())  { // Allocate a qubit.
            H(qubit);             // Put the qubit to superposition. It now has a 50% chance of being 0 or 1.
            let r = M(v);     // Measure the qubit value.
            Reset(qubit);
            return r;
        }
    }
}
```

Python code should be:
```py
import qsharp
from Quantum import QuantumRandomNumberGenerator
```
and all references of `SampleQuantumRandomNumberGenerator` would need to be replaced with `QuantumRandomNumberGenerator`.

Considering the C# samples have the same problem, could we just please change the Q# code to be:
```q#
namespace Qrng {
    open Microsoft.Quantum.Intrinsic;

    operation SampleQuantumRandomNumberGenerator() : Result {
        using(qubit = Qubit())  { // Allocate a qubit.
            H(qubit);             // Put the qubit to superposition. It now has a 50% chance of being 0 or 1.
            let r = M(v);     // Measure the qubit value.
            Reset(qubit);
            return r;
        }
    }
}
```

**Comment by geduardo** [comment]
This issue was pointed out in #680 and solved in PR #682. It should be released in the next merge from master to live. The problem was that the code for Python and C# is loaded from the samples repo, where some changes were made to stick to the Style Guide. The Q# code was written directly in the .md file in a previous version of the tutorial and therefore wasn't updated. The 'v' thing I think is just a typo. I'll keep this issue open until everything is released and works ok on Live.

**Comment by anpaz-msft** [comment]
@geduardo, I think it's now live, as the code seems to match the Q# code in the page. In case you want to close this issue now.

@cgranade, should we add some comment in `Quantum` to samples that are references from docs, so we don't forget to be careful with those changes?

**Comment by geduardo** [comment]
Oh, true. I missed that publishing PR. Thanks. Closing.
