### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by stevenlovelock** [MicrosoftDocs/quantum-docs-pr#687]
In section 1 of 'Q# operation code', 
let r = M(v); 
should be let 
r = M(qubit);

In all 3 examples of 'Creating a complete random number generator using a host program' the reference to SampleQuantumRandomNumberGenerator
should be
QuantumRandomNumberGenerator

The namespaces across both bits of code mentioned above are not consistent, so an extra using is required or they should be made the name.

I suspect one example got modified without updating the others

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-gb/quantum/quickstarts/qrng?view=qsharp-preview&tabs=tabid-vs2019#feedback)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment]
Thank you for pointing this out! You're right. I close this issue because it's a duplicate from #680 and #686. It should be solved by PR #682.
