### ISSUE TITLE
Mention other .NET languages besides C#

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#714]
Q# can also be called from F# and even VB.NET; there was [some interest in doing this](https://stackoverflow.com/q/55319901/8692657) and we even have an [example](https://github.com/microsoft/Quantum/tree/master/samples/interoperability/fsharp) of using Q# with F# in our samples. It seems worth it to at least mention other .NET languages that Q# can be called from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98484e97-4d4a-b28c-3cec-f279e4742938
* Version Independent ID: a2449d7e-a2ad-b27a-9d2c-bcf466d12fb0
* Content: [Develop with Q# + C# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/csinstall?view=qsharp-preview#feedback)
* Content Source: [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csinstall.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by geduardo** [comment]
I'll tackle this next week

**Comment by geduardo** [comment]
I guess we can close this since it's addressed in the new installation guide.
