### ISSUE TITLE
Change  Operation.qs for the Program.qs in Docs for Q#

### ISSUE THREAD

**Issue by Johnabarreto** [MicrosoftDocs/quantum-docs-pr#717]
In the latest versions of Visual Studio and vs Code the .qs its name is Program.qs not Operation.qs.

This can help new people who are introducing in Q # not to have problems in the development of their first programs with Q #

**Comment by KittyYeungQ** [comment]
Thank you for submitting this suggestion. All the programs in the examples are called Operation.qs. We will look into whether renaming them will reduce the confusion for learners.

**Comment by Johnabarreto** [comment]
Thank you so much!


[cid:image001.png@01D5EBD8.1998DF50]<https://mvp.microsoft.com/en-us/PublicProfile/5000441?fullName=John%20Alexander%20Barreto>
John Alexander Barreto
System Center and Cloud Datacenter
MVP Cloud and Datacenter management
• john.barreto@outlook.com<mailto:john.barreto@outlook.com>
• Cel:  +57-316-473-4838

**Comment by cgranade** [comment]
By way of context, the [.NET Core SDK project templates](https://github.com/microsoft/qsharp-compiler/blob/master/src/ProjectTemplates/Quantum.App1/Program.qs) and the [VS 2019 extension](https://github.com/microsoft/qsharp-compiler/blob/master/src/VisualStudioExtension/QsharpAppTemplate/Program.qs) use `Program.qs`, while the samples in microsoft/quantum tend to use `Host.qs`.

**Comment by KittyYeungQ** [comment]
@cgranade I think Johnabarreto is talking about the first experiences for new learners who land on the documentation pages that give examples in Operation.qs. For example:

![image](https://user-images.githubusercontent.com/59890648/75273784-5cc06b00-57b6-11ea-995d-8a2bbf165bf2.png)

**Comment by cgranade** [comment]
@KittyYeungQ: Agreed. In that example, the reader uses the VS2019 extension to create a new project. As per the link above, the template included with VS2019 creates `Program.qs` instead of `Operation.qs`.

**Comment by Johnabarreto** [comment]
Hi,

Yes Kitty, this is correct!



[cid:image001.png@01D5EBE1.68C38270]<https://mvp.microsoft.com/en-us/PublicProfile/5000441?fullName=John%20Alexander%20Barreto>
John Alexander Barreto
System Center and Cloud Datacenter
MVP Cloud and Datacenter management
• john.barreto@outlook.com<mailto:john.barreto@outlook.com>
• Cel:  +57-316-473-4838

**Comment by KittyYeungQ** [comment]
@cgranade any way to make the naming consistent to reduce learner confusion? Or we could call it out in the documentation.

**Comment by cgranade** [comment]
> @cgranade any way to make the naming consistent to reduce learner confusion? Or we could call it out in the documentation.

We can either change the page that @Johnabarreto pointed out, or we can change the VS 2019 and .NET Core SDK project templates to agree with the docs. I'd want @bettinaheim's input as well, since the latter would be a change to the compiler repo.

**Comment by Johnabarreto** [comment]
Thanks @cgranade<https://github.com/cgranade>, I agree that the change is not only on the mentioned page, this is just one of the different examples that contain this same problem or difference between docs and those displayed by VS or vs Code, which would not have to generate a thread for each example in Docs

[cid:image001.png@01D5EBE3.272D2030]<https://mvp.microsoft.com/en-us/PublicProfile/5000441?fullName=John%20Alexander%20Barreto>
John Alexander Barreto
System Center and Cloud Datacenter
MVP Cloud and Datacenter management
• john.barreto@outlook.com<mailto:john.barreto@outlook.com>
• Cel:  +57-316-473-4838

**Comment by KittyYeungQ** [comment]
Hi @bettinaheim let us know if you have any insight to this. Thanks.

**Comment by geduardo** [comment]
Closing this since with the new installation guide including the standalone application this issue is outdated.
