### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by glassnotes** [MicrosoftDocs/quantum-docs-pr#721]
Hi,

In the section  "Operations and Functions as First-Class Values" on the page noted below, there's a link that doesn't display properly. The relevant part currently reads:

_We will explore this further when we discuss [types in Q#] (xref:microsoft.quantum.language.type-model) more generally._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ffcea6d-4f0f-e875-50c0-3183a4196079
* Version Independent ID: 066fafd5-059b-1ab2-f579-466efb084ffe
* Content: [Operations and functions - Q# techniques - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/techniques/operations-and-functions?view=qsharp-preview)
* Content Source: [articles/techniques/operations-and-functions.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/techniques/operations-and-functions.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by cgranade** [comment]
Thanks for catching this, @glassnotes! It looks like what happened here is that a literal space was accidentally introduced between the `[ ]` and `( )`, such that the broken link warning didn't generate correctly. Should be a single-character fix, thankfully, so let me go on apply that. Thanks again for pointing that out!
