### ISSUE TITLE
Circuit diagram not visible in Dark mode

### ISSUE THREAD

**Issue by ankitbko** [MicrosoftDocs/quantum-docs-pr#733]
Quantum Circuit diagram is not visible when theme is set to dark mode. #648 doesn't seems to solve it. Has that change been deployed?

![image](https://user-images.githubusercontent.com/3169316/75649998-b4f5e200-5c7a-11ea-9969-ff85d94d228f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0986a4c4-0a4e-85aa-f803-f9b058acf166
* Version Independent ID: 4a8b6844-9d32-8759-3b59-6558285e9f6f
* Content: [Applications in the Q# standard libraries - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/applications#feedback)
* Content Source: [articles/libraries/standard/applications.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/applications.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

**Comment by geduardo** [comment]
Thank you very much! You're right, the PR #648 was for figures in other article. This page has the same problem with the transparency of SVGs. I'll remove all transparencies in the docs asap.
