### ISSUE TITLE
Error in symmetric Trotter formula

### ISSUE THREAD

**Issue by glassnotes** [MicrosoftDocs/quantum-docs-pr#749]
In the symmetric Trotter formula (3rd equation on the page), the Hamiltonians in the second product term from j = m to 1 are missing the factor of 1/2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fdb561b-2759-d054-45db-e1c3e1c00ad1
* Version Independent ID: c68ed36c-bd81-40f7-d38f-b9d7272c93da
* Content: [Simulating Hamiltonian Dynamics - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/chemistry/concepts/algorithms#feedback)
* Content Source: [articles/libraries/chemistry/concepts/algorithms.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/chemistry/concepts/algorithms.md)
* Product: **quantum**
* GitHub Login: @nathanwiebe2
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by gillenhaalb** [comment]
Thanks for letting us know! The fix should be live in the coming days (PR #751 )
