### ISSUE TITLE
visualization of equations

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/quantum-docs-pr#752]
Hi team, 
As per this issue: https://github.com/MicrosoftDocs/quantum-docs-pr.fr-FR/issues/1

The contributor reported the equations are not correctly displayed in the fr-FR page (Machine-Translated)
This is also correct for the other locales so I suspect there must be a format issue in the source that makes the format break during the translation process.

Kind regards
Microsoft DOCS International Team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6516e6bf-4cd0-2d9b-4d18-565d7dbc38b6
* Version Independent ID: a5b54d5e-8b9a-f7d5-2dac-ecd515478ba5
* Content: [Multiple qubits - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/multiple-qubits)
* Content Source: [articles/concepts/multiple-qubits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/multiple-qubits.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by geduardo** [comment]
Apparently, looking at the Markdown source code for the auto-translated version it seems that the translation software is modifying the LaTeX code and therefore leading to build errors. Some of the problems:
- The software sometimes adds a space in between $$ symbols, breaking the equation command. Then the compiler just thinks there are two empty in-line math environments before and after all the rest of the text gets compiled as plain text.
- It tries to translate sometimes some of the LaTeX commands (e.g. in the German page \ddots occasionally turned to \dpunkte).

@CeciAc Do you know who is in charge of the automated translation software? It seems like we cannot do much about this.

**Comment by Bradben** [comment]
Fixed
