### ISSUE TITLE
QDK Development Environment

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/quantum-docs-pr#753]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/quantum-docs-pr.ru-RU/issues/1

The comments below were machine-translated

@alegenyas commented 2 hours ago — with docs.microsoft.com
QDK is available for several development environments. Select your preferred setting from the following sections:
Installing Q # for C #:
Installing Q # for Python
Installing Q # for Jupyter Notebook

Hello Tell me please. Can I install all three environments at the same time, for more effective interaction and implementation of different projects on 1 platform (foundation). In fact, it would be very convenient for us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/#feedback)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by geduardo** [comment]
Hi @CeciAc, @alegenyas! In principle, there shouldn't be any incompatibility between environments, so installing them at the same time is indeed possible. 

Автоматический русский перевод:

Привет @CeciAc, @alegenyas! В принципе, не должно быть несовместимости между средами, поэтому их установка в одно и то же время действительно возможна.
