### ISSUE TITLE
The older links to UserVoice in the release notes, no longer work - have they moved?

### ISSUE THREAD

**Issue by DOMARS** [MicrosoftDocs/quantum-docs-pr#761]
The older links to UserVoice in the release notes, no longer work - have they moved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88063b8-bb4f-1d76-7ea9-d5ca7f28cbfd
* Version Independent ID: 22d0cb8d-9272-7243-8052-e16c107581a4
* Content: [Quantum Development Kit preview release notes - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/relnotes/)
* Content Source: [articles/relnotes/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/relnotes/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by Bradben** [comment]
Remove links from readme
