### ISSUE TITLE
Syntax highlighting for Q# is out of date

### ISSUE THREAD

**Issue by cgranade** [MicrosoftDocs/quantum-docs-pr#762]
As described by @marshallsa, @bettinaheim, @tcNickolas, and @kittyyeungq, the syntax highlighting definitions for Q# code are out of date, and do not include features introduced since Q# 0.1. If possible, it would be good to update these definitions to include recent changes and features.

> @Bradben @natke The colorization for the newly introduced keyword "internal" is not currently matching the one for the existing keywords "operation", "function", and "newtype". the current syntax highlighting reflects Q# syntax as of November 2017 (Q# 0.1), and not any recent changes; keywords like “Unit,” “is,” “Adj,” etc. are also not highlighted.

> _Originally posted by @KittyYeungQ in https://github.com/MicrosoftDocs/quantum-docs-pr/pull/755_

**Comment by geduardo** [comment]
Is there any reference or guide on how to contribute to the syntax highlighting definitions? I found this repo, but I don't know exactly how to contribute.
https://github.com/msr-quarc/qsharp.sty

Maybe we should considerate adding a section to the Contributors Guide

**Comment by tcNickolas** [comment]
Here is a summary (to the best of my knowledge). The docs *should* be using the first one, but the question is how to update it - there is no process that I'm aware of.

We have several syntax highlight tools, which need to be updated whenever we change the language.

1. TextMate grammar for Visual Studio/VS Code extensions.

The grammar is generated based on [tmLanguage.json file template](https://github.com/microsoft/qsharp-compiler/blob/master/src/VSCodeExtension/syntaxes/qsharp.tmLanguage.json.v.template).

[More information on TextMate grammars].

2. CodeMirror mode for Jupyter Notebooks.

The mode is [kernel.ts](https://github.com/microsoft/iqsharp/blob/master/src/Jupyter/client/kernel.ts). It is used in all Q# Notebooks, as well as in code-in-browser windows in the online course at Brilliant.org.

[More information on CodeMirror modes](https://codemirror.net/doc/manual.html#modeapi).

3. LaTeX syntax highlight.

Maintained in a separate GitHub repository: https://github.com/msr-quarc/qsharp.sty . This is used in a package that provides syntax highlight for Q# code snippets in papers.

4. code-prettify extension for Quantum Computing SE.

The extension was posted as an [answer here](https://quantumcomputing.meta.stackexchange.com/questions/386/syntax-highlighting-for-quantum-programming-languages) to enable Q# syntax highlight on Quantum Computing SE (not enabled yet). Originally it was intended to be contributed to code-prettify repository and maintained there, but code-prettify doesn't accept new language contributions.

**Comment by geduardo** [comment]
Oh, that is very useful information to start with! Thanks @tcNickolas!

**Comment by KittyYeungQ** [comment]
See new issue #768
