### ISSUE TITLE
Extra bracket in Measure([PauliY], [q]])

### ISSUE THREAD

**Issue by SandraVeres** [MicrosoftDocs/quantum-docs-pr#766]
There is an typo in Measure([PauliY], [q]]), an extra ] bracket. It's in the text just above the first Q# example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fa8b49-db57-3ecb-0f9b-9e32feee3ebc
* Version Independent ID: bc76d802-3855-b0ce-4131-f44852e7d419
* Content: [Pauli Measurements - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements#feedback)
* Content Source: [articles/concepts/pauli-measurements.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/pauli-measurements.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by gillenhaalb** [comment]
Good catch! Thanks for the heads up, the fix should be live soon!
