### ISSUE TITLE
Q# syntax highlighting out of date on docs.microsoft.com

### ISSUE THREAD

**Issue by natke** [MicrosoftDocs/quantum-docs-pr#768]
See this page, for example, where the `internal` keyword is not highlighted: https://review.docs.microsoft.com/en-us/quantum/language/file-structure?branch=master#internal-declarations

**Comment by natke** [comment]
Also `unit`, `Adj`

**Comment by cgranade** [comment]
Also not highlighted:

- `as` in `open` statements (https://docs.microsoft.com/quantum/language/file-structure)
![image](https://user-images.githubusercontent.com/31516/77458034-c6826380-6dba-11ea-9fb6-3734b7814d4c.png)
- `is` in operation type declarations (https://docs.microsoft.comquantum/language/statements#conjugations)
![image](https://user-images.githubusercontent.com/31516/77458172-ff223d00-6dba-11ea-992f-15d5db5adfa4.png)
- `within` and `apply` (https://docs.microsoft.comquantum/language/statements#conjugations)
![image](https://user-images.githubusercontent.com/31516/77458220-13fed080-6dbb-11ea-82dc-1b46e0bfde66.png)

I didn't check yet, sorry, but I suspect `BigInt` also isn't highlighted as a type.

**Comment by natke** [comment]
Thank you @cgranade!

**Comment by geduardo** [comment]
Looks like we can close this, right? @KittyYeungQ, @cgranade
