### ISSUE TITLE
Export PDF

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#776]
Is it possible to export docs into PDFs? 
support export as PDF on some pages (below the TOC on the left). It'd be great to enable this option for the Quantum documentation to make offline study and printing easier.

**Comment by cgranade** [comment]
We used to enable this, but it didn't play well with MathJax such that it was disabled. I agree, though, it would be good to re-enable once we can get LaTeX embedding working more robustly.

**Comment by geduardo** [comment]
Can you explain what do you mean by "get LaTeX embedding working more robustly" @cgranade? Do we have an example of it not working properly apart from the issue with the automatically translated pages?

**Comment by geduardo** [comment]
Closing since @Bradben added this feature. However, as @cgranade the LaTeX formulas don't render in the PDF. Opening a new issue to track that.
