### ISSUE TITLE
Sample code should have Reset

### ISSUE THREAD

**Issue by MikeMKH** [MicrosoftDocs/quantum-docs-pr#780]
The sample code should have release the qubits that using is obtaining.  Being new to Q# I did not know until I found a StackOverflow answer on the error message "Microsoft.Quantum.Simulation.Simulators.Exceptions.ReleasedQubitsAreNotInZeroState: Released qubits are not in zero state.".  Since most people are new to Q# who are reading this so the sample code should have Reset in it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e3df2d-e020-61e8-5653-54aae83ae63d
* Version Independent ID: 9c43aeec-9766-fa11-81c8-589156cc5d97
* Content: [Q# techniques - Putting it all together - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/techniques/putting-it-all-together#feedback)
* Content Source: [articles/techniques/putting-it-all-together.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/techniques/putting-it-all-together.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by geduardo** [comment]
Yes, you're right. I opened a PR to fix it. Thank you very much!
