### ISSUE TITLE
Excellent - with reservations

### ISSUE THREAD

**Issue by FrancisKing3** [MicrosoftDocs/quantum-docs-pr#781]
This page explicitly states how multiple qubits are combined.

Although it needs to have some explicit calculations to show how the tensor products are worked out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6516e6bf-4cd0-2d9b-4d18-565d7dbc38b6
* Version Independent ID: a5b54d5e-8b9a-f7d5-2dac-ecd515478ba5
* Content: [Multiple qubits - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/multiple-qubits#feedback)
* Content Source: [articles/concepts/multiple-qubits.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/multiple-qubits.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by geduardo** [comment]
Thank you for your feedback, @FrancisKing3 ! I agree. I'll create a PR to add a short explanation.
