### ISSUE TITLE
Data Visualization 

### ISSUE THREAD

**Issue by theRomanMercury** [MicrosoftDocs/quantum-docs-pr#795]
I just got interested in quantum computing and coding also examined the samples.
Is it possible to visualize data in visual studio code with quantum computing?

**Comment by geduardo** [comment]
Hi @theRomanMercury. First, let me welcome you to the quantum computing community! 
I need you to be more specific about the data you want to visualize. Visual studio code is a source-code editor that you can use to program in many languages, many of them with data visualization tools. You can use those tools to plot data related to quantum computing. For example, in the sample to showcase the Quantum Machine Learning library we use the Python library Matplotlib to plot the classification results: https://github.com/theRomanMercury/Quantum/tree/master/samples/machine-learning/half-moons.
Does this help you? What kind of data do you want to visualize?

**Comment by theRomanMercury** [comment]
Hi @geduardo. Thank you for your answer, this topic really excites me. I am working on financial charts and indicators. I want to visualize the realized performance with the criteria set on the data set.

**Comment by geduardo** [comment]
@theRomanMercury in that case I recommend you to use Python with Matplotilb and Pandas to visualize your datasets. Here you have an introduction: https://towardsdatascience.com/a-guide-to-pandas-and-matplotlib-for-data-exploration-56fad95f951c

**Comment by theRomanMercury** [comment]
Thank you for the resource. How can I use Q# for optimization?

**Comment by theRomanMercury** [comment]
@geduardo 

for example; 

if price of the share is above 144 exponential moving average 
and 144 EMA is below bollinger upper band 
also if the RSI of the share at (t) is high than (t-1) 
pick the share and compering it with the market performance at that day, 
then saving the diffence to that day's record.

I have daily indicator datas, conditions can be increased for better results, but I do not know how to back test it or optimize for the best solution. 

thank you for your interest

**Comment by geduardo** [comment]
Sorry for the late reply @theRomanMercury, but my knowledge of mathematical economy is very limited (and I fear this section is not the right place to discuss this since this Issues section is reserved for issues related to the Q# documentation). Nonetheless, I encourage you to open a question in [Quantum Computing StackExchange](https://quantumcomputing.stackexchange.com) website, where maybe someone can answer your doubts.
