### ISSUE TITLE
update guide

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#800]
The current update guide is incorrect. Needs new instruction: https://review.docs.microsoft.com/en-us/quantum/install-guide/update?branch=live

**Comment by cgranade** [comment]
Which new instructions are required in particular? It looks like we need to change the target framework from `netcoreapp3.0` to `netcoreapp3.1`, but was there something else as well?

**Comment by gillenhaalb** [comment]
> Which new instructions are required in particular? It looks like we need to change the target framework from `netcoreapp3.0` to `netcoreapp3.1`, but was there something else as well?

Just updated in #813

**Comment by geduardo** [comment]
We don't close this since we still need to add the procedure to update the sdk version on the project files.

**Comment by KittyYeungQ** [comment]
@ricardo-espinoza is writing a script.
