### ISSUE TITLE
More generic generator

### ISSUE THREAD

**Issue by vlaa1** [MicrosoftDocs/quantum-docs-pr#817]
Hello, I was wondering how could one pass a more generic generator H to the evolution set? In the documentation I only found how to pass an H which is made of combinations of Paulis/tensors of Paulis, but what if one wants to pass in, say, an 8x8 matrix H?

Thanks for the help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc46448-8d60-c389-f983-8bd28e3d4da6
* Version Independent ID: 70f41004-de68-86bd-9afd-54df9db5c0a5
* Content: [Data structures in the Q# standard libraries - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/libraries/standard/data-structures)
* Content Source: [articles/libraries/standard/data-structures.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/standard/data-structures.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **martinro@microsoft.com**

**Comment by rmshaffer** [comment]
Hi @vlaa1, thanks for the question! A very similar question was also posted to StackOverflow recently:
https://quantumcomputing.stackexchange.com/questions/11913/generic-matrix-exponential-in-q
Please check out the answer there, and feel free to follow up with any additional questions!
