### ISSUE TITLE
Non-consistent phraseology: Next steps vs What's next?

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#823]
**Problem:** the documentation is not consistent with the use of "Next steps" or "What's next?".
**Proposed solution**: Change every "What's next?" or similar to "Next steps".

Tagging @Bradben, @cjgronlund, and @KittyYeungQ to decide. What is the standard form in Azure docs?

**Comment by Bradben** [comment]
"Next steps" is the standard

**Comment by KittyYeungQ** [comment]
The pages that haven't been updated: 
https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-python
https://docs.microsoft.com/en-us/quantum/user-guide/basics
https://docs.microsoft.com/en-us/quantum/user-guide/language/types
https://docs.microsoft.com/en-us/quantum/user-guide/language/expressions
https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/file-structure
https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/operations-functions
https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/variables
https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/working-with-qubits
https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/control-flow
https://docs.microsoft.com/en-us/quantum/libraries/machine-learning/load?tabs=tabid-python
