### ISSUE TITLE
Reasoning and link

### ISSUE THREAD

**Issue by jkovzels** [MicrosoftDocs/quantum-docs-pr#829]
Not easy to understand the material without prior knowledge in linear algebra (?). So I left the page without full understanding of the material and I'm not how it is important, because content and reasoning is not provided. 
Plus, links to wikipeadia are super discouraging, Wiki does not try to teach you, it just states the facts. Consider replacing wiki links with links to Khan Academy or similar resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices in quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by tcNickolas** [comment]
Have you checked out https://github.com/Microsoft/QuantumKatas/? They offer an introduction to the linear algebra as one of the two introductory topics and then segue into how these are used in the quantum computing to describe the quantum states and the operations on them.

**Comment by geduardo** [comment]
Thanks for your feedback @jkovzels! We're aware of the difficulty for newcomers to understand the Linear Aglebra page and we're working on creating a new more accessible resource. For the moment I highly recommend you follow the great resources @tcNickolas provides in the comment above.
