### ISSUE TITLE
Running on VS Code

### ISSUE THREAD

**Issue by mohangude** [MicrosoftDocs/quantum-docs-pr#841]
Can you teach me how to setup my code on VS Code?

What I did was open up the Terminal. Then I copied from the C# Command Line and pasted
"
dotnet new console -lang Q# --output Bell
cd Bell
"
into the Terminal. But then I received an error saying
"
Creating this template will make changes to existing files:
  Overwrite   Program.qs
  Overwrite   Bell.csproj

Rerun the command and pass --force to accept and create.
"
this in the terminal.

**Comment by poychang** [comment]
@mohangude I believe you executed `dotnet new console -lang Q# --output Bell` twice
So, nothing wrong with your commands, and you are acutely ready to go with your Bell project 
![image](https://user-images.githubusercontent.com/4879879/95109317-0913f800-076f-11eb-90b1-6030df549685.png)
