### ISSUE TITLE
Access to Q# namespace not automatic with instructions

### ISSUE THREAD

**Issue by gillenhaalb** [MicrosoftDocs/quantum-docs-pr#842]
I followed the instructions to create the Q# library, add the C# console project, and add the reference from the host program, but noticed that these automatically titled the Q# namespace `quantum`, and the C# program uses `namespace host`. The interoperability only seems to work when either the namespace titles match (e.g. replace "host" with "quantum" in the C# file), or including a `using quantum;` statement at the opening of the C# file.

People proceeding to tutorials, such as the QRNG we link to, might not immediately run into this this error if they fully copy and paste the Q# and C# code blocks we provide (because matching namespace titles are included therein). However, it seems like a frustration waiting to happen for many people, so I think we definitely need to mention this nuance somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40563a4d-6e4d-5fee-f930-355e40604e01
* Version Independent ID: 76518260-3988-ea07-3deb-a52f51fe94e2
* Content: [Develop with Q# and .NET - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/csinstall?tabs=tabid-cmdline%2Ctabid-csharp)
* Content Source: [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csinstall.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by gillenhaalb** [comment]
@cgranade @anpaz-msft @bettinaheim @tcNickolas, I came across this while writing #840 (and mentioned it therein). 

Will be adding a note to the page, but don't know enough about the behind-the-scenes details to be sure about how to frame it. Is it a deliberate feature?

**Comment by cgranade** [comment]
Roughly, interoperability between Q# and .NET languages like C# works by generating a .NET class for each Q# entry point that can be used to dispatch that entry point to a target machine for execution. These .NET classes have fully-qualified names that match the fully-qualified names of each Q# callable exposed for interop, such that either an explicit namespace name or a `using` statement has to be used on the C# side, as you note. (BTW, this is similar how the Python package uses `sys.meta_path` to dynamically create Python modules for each Q# namespace.)

From that perspective, if following the instructions and using the templates for C# interop results in those stub classes not being imported with appropriate `using` statements, I agree that's confusing and is a bug in either docs, templates, or both.
