### ISSUE TITLE
Clarify sub-typing behavior in Q#

### ISSUE THREAD

**Issue by bettinaheim** [MicrosoftDocs/quantum-docs-pr#845]
**Is your feature request related to a problem? Please describe.**
Consider the following snippet of code:

```qsharp
function fooA( a : (Unit => Unit is Adj) ) : Unit {}
function foo( a : (Unit => Unit) ) : Unit {}
function Bar() : Unit {
    let x = [foo, fooA];
    let z = [(1, foo), (2, fooA)];
    let y = [(foo, foo), (fooA, fooA)];
    // (QS5002) Array items must have a common base type.
    let w = [[foo], [fooA]]; // QS5002 error
}
```
Expressions `let x ...`, `let y ...`, `let z ...` compile without an error, and `let w=...` causes an error. 
It seems like `(Unit => Unit)` is a supertype of `(Unit => Unit is Adj)`, however 
`(Unit => Unit)[]` and  `(Unit => Unit is Adj)[]` have no common base type. 

**Describe the solution you'd like**
I would like the code above to compile without an error. 

**Describe alternatives you've considered**
Update the documentation at https://docs.microsoft.com/en-us/quantum/user-guide/language/types#operation-and-function-types to clarify that above is intended behavior

**Comment by bettinaheim** [comment]
Originally filed by @vadym-kl in https://github.com/microsoft/qsharp-compiler/issues/433.

**Comment by KittyYeungQ** [comment]
explicitly state that arrays are invariant
