### ISSUE TITLE
Spelling Error on Types in Q#

### ISSUE THREAD

**Issue by ChiragTutlani** [MicrosoftDocs/quantum-docs-pr#847]
In sub-heading primitive types on point number 5, it is written 'where step is options', which should have been 'where step is optional'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09f76d3-5d53-f5d3-54e0-a2e31b3e6fd3
* Version Independent ID: 20ac3f86-7520-fe54-8585-8c4b7c44ad4b
* Content: [Types in Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/language/types)
* Content Source: [articles/user-guide/language/types.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/language/types.md)
* Product: **quantum**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec@microsoft.com**

**Comment by geduardo** [comment]
Closed by #848
