### ISSUE TITLE
Quantum Platform

### ISSUE THREAD

**Issue by andrewkohmw** [MicrosoftDocs/quantum-docs-pr#853]
Finally a great platform for Quantum developers. Simple and concise format makes easy reading. Great start! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592d8d18-eb52-7018-f128-41b6a7934604
* Version Independent ID: 5850b45d-123b-8e41-c46a-b0e357c806a7
* Content: [Contributing to the Microsoft Quantum Development Kit - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/contributing/#feedback)
* Content Source: [articles/contributing/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/contributing/index.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by geduardo** [comment]
Thanks! Great to hear this! ❤️
