### ISSUE TITLE
Are there patterns in the numbers created with qrng by entangled qubits?

### ISSUE THREAD

**Issue by theRomanMercury** [MicrosoftDocs/quantum-docs-pr#854]
Hello there,

I want to examine the graph of 2 sets consisting of 1000 numbers created with quantum random number generator which created by entangled qubits and see if there is a pattern in the randomly generated number series.

How can I do this with Q #?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?tabs=tabid-csharp)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by theRomanMercury** [comment]
So by doing that I think,I can entangle two qubits in Sample Quantum Random Number Generator .

operation SampleQuantumRandomNumberGenerator() : Result {
// Allocate two qubits
using ((q1, q2) = (Qubit(), Qubit()))  {
    // Prepare Bell state (|00⟩ + |11⟩) / sqrt(2) on them
    H(q1);
    CNOT(q1, q2);
    // The measurement results are going to be correlated: you get 0,0 in 50% of the cases and 1,1 in 50%
    return (MResetZ(q1) == Zero ? 0 | 1, 
            MResetZ(q2) == Zero ? 0 | 1);
}
But how can I use this 2 qubits in here for getting 2 sets consisting of 1000 numbers between 0 and 100 ?

operation SampleRandomNumberInRange(max : Int) : Int {
    mutable bits = new Result[0];
    for (idxBit in 1..BitSizeI(max)) {
        set bits += [SampleQuantumRandomNumberGenerator()];
    }
    let sample = ResultArrayAsInt(bits);
    return sample > max
           ? SampleRandomNumberInRange(max)
           | sample;
}

@EntryPoint()
operation SampleRandomNumber() : Int {
    let max = 100;
    Message($"Sampling a random number between 0 and {max}: ");
    return SampleRandomNumberInRange(max);
}

**Comment by theRomanMercury** [comment]
So by doing that I think,I can entangle two qubits in Sample Quantum Random Number Generator .

```
namespace Qrng 
{
    open Microsoft.Quantum.Convert;
    open Microsoft.Quantum.Math;
    open Microsoft.Quantum.Measurement;
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;
    
    operation SampleQuantumRandomNumberGenerator() : Result {
    // Allocate two qubits
    using ((q1, q2) = (Qubit(), Qubit()))  {
        // Prepare Bell state (|00⟩ + |11⟩) / sqrt(2) on them
        H(q1);
        CNOT(q1, q2);
        // The measurement results are going to be correlated: you get 0,0 in 50% of the cases and 1,1 in 50%
        return (MResetZ(q1) == Zero ? 0 | 1, 
                MResetZ(q2) == Zero ? 0 | 1);
    }
}
```

But how can I use this 2 qubits in here for getting 2 sets consisting of 1000 numbers between 0 and 100 ?

```
{
operation SampleRandomNumberInRange(max : Int) : Int {
    mutable bits = new Result[0];
    for (idxBit in 1..BitSizeI(max)) {
        set bits += [SampleQuantumRandomNumberGenerator()];
    }
    let sample = ResultArrayAsInt(bits);
    return sample > max
           ? SampleRandomNumberInRange(max)
           | sample;
}

@EntryPoint()
operation SampleRandomNumber() : Int {
    let max = 100;
    Message($"Sampling a random number between 0 and {max}: ");
    return SampleRandomNumberInRange(max);
}
```

**Comment by tcNickolas** [comment]
I answered this question on [Quantum Computing StackExchange](https://quantumcomputing.stackexchange.com/questions/12130/are-there-patterns-in-the-numbers-created-with-qrng-by-entangled-qubits/12142#12142), so I'll close the issue for now to save @geduardo some work :-) 

@theRomanMercury, please feel free to follow up if you have more questions!
