### ISSUE TITLE
How can `|a|²+|b|²+|c|²+|d|²=1`?

### ISSUE THREAD

**Issue by ms-maxvollmer** [MicrosoftDocs/quantum-docs-pr#855]
Hi! I am not super deep into all the maths, so I might just overlook some crucial detail, but I stumbled over the `|a|²+|b|²+|c|²+|d|²=1` bit and can't wrap my head around it. Don't `|a|²+|b|²` and `|c|²+|d|²` both have to equal 1? So shouldn't the entire sum be 2? Did you mean to write `|ac|²+|ad|²+|bc|²+|bd|²=1`? Or what am I missing? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb830cc-7d9b-c13e-4652-115352ea1e29
* Version Independent ID: f9484b57-1dc8-06a9-ac6d-cdc7c4769981
* Content: [Linear algebra for quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/overview/algebra-for-quantum-computing)
* Content Source: [articles/overview/algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/overview/algebra-for-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by geduardo** [comment]
Hi @ms-maxvollmer, you're right! The correct formula should be:
´|ac|²+|ad|²+|bc|²+|bd|²=1´
since for a given orthogonal basis all probabilities should sum up to one. We are working on a remake of the linear algebra section, so I'll close this issue when we submit that.

**Comment by ms-maxvollmer** [comment]
Thanks for the quick reply and confirming! That puts my mind at ease xD

**Comment by geduardo** [comment]
Closing since it's solved by #861
