### ISSUE TITLE
Q# kernel not connecting(Jupyter Notebook)

### ISSUE THREAD

**Issue by n33r4j** [MicrosoftDocs/quantum-docs-pr#857]
I recently updated my iqsharp(from 0.10 to 0.11) for jupyter notebooks (via Anaconda) and ever since, the Q# kernel stopped connecting when I open a new or existing Q# notebook(Python works fine). I have tried uninstalling and reinstalling jupyter notebook as well as iqsharp but nothing seems to have changed. 
I think it may have something to do with "Access to the path 'C:\Users\neera\Application Data' is denied".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7f7964-eb2b-502d-470d-91f826aea2ff
* Version Independent ID: d74f059a-e3a3-29e8-ba53-cef7c831f010
* Content: [Develop with Q# Jupyter Notebooks - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/qjupyter)
* Content Source: [articles/install-guide/qjupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/qjupyter.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by geduardo** [comment]
Hi @n33r4j! I cloned your thread in the IQ# server GitHub. There they might know how to help you! Thanks! https://github.com/microsoft/iqsharp/issues/149

**Comment by n33r4j** [comment]
Thanks!
