### ISSUE TITLE
Equation claimed is not a tautology

### ISSUE THREAD

**Issue by cjiii** [MicrosoftDocs/quantum-docs-pr#859]
The unnumbered equation below is not a tautology as claimed:

(α|ψ⟩+β|ϕ⟩)⊗(γ|χ⟩+δ|ω⟩)=αγ|ψ⟩|χ⟩+αδ|ψ⟩|ω⟩+βγ|ϕ⟩|χ⟩+βδ|ϕ⟩|ω⟩. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338eacdb-6359-46bd-c784-3e828a6b2b30
* Version Independent ID: ea8a2905-7103-b4ff-8202-335f8f6d8275
* Content: [Dirac notation - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/dirac-notation)
* Content Source: [articles/concepts/dirac-notation.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/dirac-notation.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by KittyYeungQ** [comment]
There may need to be some clarification to the convention of the "tensor product" used here, with relation to https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices and clarify with "Kronecker product".

**Comment by gillenhaalb** [comment]
Assigning @geduardo as this is likely addressed in his linear algebra section re-work
