### ISSUE TITLE
Coding Chaos

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/quantum-docs-pr#860]
@gchling commented 2 days ago

Coding Chaos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices in quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by KittyYeungQ** [comment]
@CeciAc @srvbpigh  Thank you for transferring the issue. However there doesn't seem to be actual issue submitted in Coding Chaos #2 "[在此处输入反馈]" This part was left empty.
![image](https://user-images.githubusercontent.com/59890648/82885308-4953a600-9f45-11ea-9ada-03abf7cfdb38.png)

**Comment by geduardo** [comment]
Hi @CeciAc! Thanks for filling the issue. This issue seems to be related with https://github.com/MicrosoftDocs/quantum-docs-pr/issues/752. Do you know who is in charge of the automated translation?

**Comment by KittyYeungQ** [comment]
Addressing with #871

**Comment by Bradben** [comment]
Fixed
