### ISSUE TITLE
codes are not running

### ISSUE THREAD

**Issue by theRomanMercury** [MicrosoftDocs/quantum-docs-pr#868]
Hello,

I apply the steps mentioned on the page in Visual Studio Code, when I run the codes with dotnet run, the output is Hello quantum wolrd!

Can you help me ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/qrng?tabs=tabid-qsharp)
* Content Source: [articles/quickstarts/qrng.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/qrng.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment]
Hi! It looks like you didn't saved your `*.qs` and the compiler is taking the original code from the template. Once you modified the code, please be sure you save it (in windows you can press `Ctrl`+`S`.

Tell me if this helps,

**Comment by theRomanMercury** [comment]
Thank you so much, it worked.
