### ISSUE TITLE
I think there is typos Q# page

### ISSUE THREAD

**Issue by adnaan1703** [MicrosoftDocs/quantum-docs-pr#872]
[Enter feedback here]
There are these in the doc
```
C# with Visual Studio
C# with VS Code
C# with the command line
```

Shouldn't these be Q# and not C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2273c883-0cf3-4f02-e543-088ae630cc81
* Version Independent ID: a3a2e7b6-c654-dbf2-97ab-efd89487822a
* Content: [Learn how to create a Q# project with the Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/how-to-guides/create-qsharp-project#create-a-c-project-using-vs-code)
* Content Source: [articles/how-to-guides/create-qsharp-project.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/how-to-guides/create-qsharp-project.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by gillenhaalb** [comment]
In this case specifically, those are meant to be "C#", as they are referring to the use of Q# with a C# host program. This page has actually been deprecated, and the relevant instructions are now at each respective page in the [install guide](https://docs.microsoft.com/en-us/quantum/install-guide/). 

We will take action to make sure that this page is clearly marked as deprecated, thanks so much for providing feedback!
