### ISSUE TITLE
Missing instructions on running Q# from IDEs other than VS/VS Code

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#883]
There used to be a section with instructions on how to run Q# from pure command line, regardless of the IDE, but it is gone. Based on user feedback, it is not sufficient to recommend using VS/VS Code, we also need to provide instructions on how to run Q# from other IDEs, even if they don't provide rich functionality, because there will be users who are used to their IDEs and don't want to switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e509ca-7867-e8f0-45f1-bb20d27ad232
* Version Independent ID: a6a281f8-53e0-8bdb-2b6e-8228fc2204f2
* Content: [Develop with Q# command line applications - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/standalone)
* Content Source: [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/standalone.md)
* Product: **quantum**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by KittyYeungQ** [comment]
We have them here:
![image](https://user-images.githubusercontent.com/59890648/83667627-fc1fa600-a5ce-11ea-96bf-75369e2e2e05.png)
This is part of the discussion and conclusion from May release.

**Comment by KittyYeungQ** [comment]
Also see PR #840

**Comment by KittyYeungQ** [comment]
It's captured up front here: https://docs.microsoft.com/en-us/quantum/install-guide/ for people coming for the first time and installing. They see those options.

**Comment by gillenhaalb** [comment]
I think I get what @tcNickolas is saying, correct me if I'm wrong. @KittyYeungQ suppose I wanted to use Q# in a _non_-VS/VS Code IDE. Regardless of whether I want to pair it with a host program or use the Q# command line application, there are currently no instructions telling me how I can even get the QDK, let alone create a Q# project.

Even the most IDE-agnostic set of instructions (those for Python) only gives this option for installing the QDK:
![image](https://user-images.githubusercontent.com/47889725/83671493-18264600-a5d5-11ea-9ca9-0856dfab0a72.png)

Same goes for getting the QDK on all other pages. Further, even on the command line application page, the _only_ ways in which I'm told how to create/run a Q# project are by accessing the templates through the VS Code or VS interface:
![image](https://user-images.githubusercontent.com/47889725/83672120-10b36c80-a5d6-11ea-80a1-03245a952d0e.png)

**Comment by KittyYeungQ** [comment]
Got it. Thanks. But that's what we have, right? Do we have QDK extension for other IDEs?

**Comment by tcNickolas** [comment]
@gillenhaalb Exactly! Thank you for detailed clarification :-)

We don't have QDK extensions for other IDEs, but you can use Q# without an extension perfectly fine! You can do running/testing/project creation from command line, and it doesn't matter where you edit the code. There is, for example, [syntax highlight for Sublime](https://gitgud.io/Xellos/qsharp-sublime-syntax) developed by one of our users, which makes the experience there better. We shouldn't make it look like it's absolutely impossible to use Q# with other IDEs.

**Comment by cgranade** [comment]
By way of agreement with @tcNickolas, the QDK extensions for VS2019 and VS Code are very helpful, but are not **required** to develop in Q#. You can be an effective quantum developer in whatever IDE or editor works best for you.

**Comment by KittyYeungQ** [comment]
Then we should document that. If I didn't know, learning from the current docs, then others wouldn't know either. Thank you for pointing it out.
