### ISSUE TITLE
Bloch sphere angle conventions

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#894]
[Enter feedback here]

I'm a bit confused by the definition of R_z, why it is a function of theta. By convention of the qubit Bloch Sphere in the wikipedia page we refer to, shouldn't R_z be a function of phi?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23545203-bbb6-f7f2-5100-98806f3c14f8
* Version Independent ID: aba3f750-bb33-f896-1a71-463d6482b1b7
* Content: [The qubit in quantum computing - Microsoft Quantum](https://review.docs.microsoft.com/en-us/quantum/concepts/the-qubit?branch=tensor-product)
* Content Source: [articles/concepts/the-qubit.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/tensor-product/articles/concepts/the-qubit.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by cgranade** [comment]
The use of _θ_ in the description of the unitary matrix 𝑅_z matches the name of the `theta` input to the [`Microsoft.Quantum.Intrinsic.Rz` operation](https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.intrinsic.rz). We've similarly used `theta` as the input name for `Rx`, `Ry`, and `R1` intrinsic operations. From that perspective, I'd suggest sticking with _θ_ for consistency.

![image](https://user-images.githubusercontent.com/31516/83952481-f5bb4500-a7ed-11ea-8d11-4d0ed2f70d0b.png)

**Comment by KittyYeungQ** [comment]
Understand the naming convention. The definition of theta here is the angle about the z-axis. But the theta defined in Rx and Ry are angles about the x- and y- axes (which are the same theta). If someone wants to change both the angle about the z-axis and the angle about x-axis, they are expected to use two different thetas, correct?

**Comment by geduardo** [comment]
Closing this. Please open if further clarification is needed.
