### ISSUE TITLE
Entanglement tutorial uses outdated project setup

### ISSUE THREAD

**Issue by eddieschoute** [MicrosoftDocs/quantum-docs-pr#898]
In the [C# command line setup](https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-csharp), the command `dotnet new console -lang Q# --output Bell` does not generate a C# file (Driver.cs) as expected from the text. This should probably be updated to reflect 
the need to setup two project in accordance with https://docs.microsoft.com/en-us/quantum/install-guide/csinstall?tabs=tabid-cmdline%2Ctabid-csharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e984fdb6-63e6-92ac-f794-8a15a5092559
* Version Independent ID: bcd9a2e2-0b07-514e-5b43-8b3e092669ce
* Content: [Explore entanglement with Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-csharp)
* Content Source: [articles/quickstart.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstart.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by geduardo** [comment]
Hi @eddieschoute, you're right, that tutorial uses the templates of a previous version of the QDK and it doesn't reflect recent changes where the Driver.cs file is no longer necessary. It should be updated. Thank you!
