### ISSUE TITLE
Private or Internal Names

### ISSUE THREAD

**Issue by msoeken** [MicrosoftDocs/quantum-docs-pr#908]
The section on *Private or Internal Names* should be revised to recommend the use of the `internal` keyword rather than prefixing with `_`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc4b9d4-0214-5c5c-4528-20d345c87a2d
* Version Independent ID: 4e5ad251-dec1-1e76-7089-eb8862d24160
* Content: [Microsoft Q# Style Guide - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/contributing/style-guide?tabs=guidance)
* Content Source: [articles/contributing/style-guide.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/contributing/style-guide.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **chgranad**

**Comment by geduardo** [comment]
Thanks for filling the issue. I addressed this in #909 but I can't add you as a reviewer since you're not in the list of collaborators for this repo (we can add you I think).
