### ISSUE TITLE
Select Q#: Install project templates. - Doesn't work

### ISSUE THREAD

**Issue by Lainad27** [MicrosoftDocs/quantum-docs-pr#912]
When I Click View -> Command Palette, Select Q#: Install project templates, nothing happens, although the first time I did it it said "Activating Extensions" on the bottom left of the screen. "Project templates installed successfully" never displays. And yes, I have installed the "Microsoft Quantum Development Kit for Visual Studio Code" Extension, on Visual Studio win x64-1.46.0. and .NET Core 3.1.5-win-x64. ("Run Apps"). Therefore, I can not complete the setup process and can't code with Q# using VS code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e509ca-7867-e8f0-45f1-bb20d27ad232
* Version Independent ID: a6a281f8-53e0-8bdb-2b6e-8228fc2204f2
* Content: [Develop with Q# command line applications - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/standalone)
* Content Source: [articles/install-guide/standalone.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/standalone.md)
* Product: **quantum**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by geduardo** [comment]
Hi @Lainad27! Sorry for the inconvenience. Have you tried to continue the setup process even if the pop-up confirming the installation of the templates never shows up?

**Comment by Lainad27** [comment]
> Hi @Lainad27! Sorry for the inconvenience. Have you tried to continue the setup process even if the pop-up confirming the installation of the templates never shows up?

I have, (Q#: Install project templates.) nothung prompted / happened. I did complete the installation using the normal Visual Studio, (and it workd) so I just kinda gave up on VS Code. Don't feel pressured to help me :).

**Comment by KittyYeungQ** [comment]
@bettinaheim would this be something compiler can address?
