### ISSUE TITLE
There is no Q# template in Visual Studio 2019 Version 16.6.2

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/quantum-docs-pr#919]
There is no Q# template in Visual Studio 2019 Version 16.6.2
https://1drv.ms/u/s!AlUZkNIm6J4hhRcvBb6jEOL8rEZD?e=sroyC6

The step 
Go to File -> New -> Project
Type "Q#" in the search box

Will not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40563a4d-6e4d-5fee-f930-355e40604e01
* Version Independent ID: 76518260-3988-ea07-3deb-a52f51fe94e2
* Content: [Develop with Q# and .NET - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/csinstall?tabs=tabid-vs2019%2Ctabid-csharp)
* Content Source: [articles/install-guide/csinstall.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/csinstall.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by geduardo** [comment]
HI @chanmmn, did you install the QDK? 

Installation guide: https://docs.microsoft.com/en-us/quantum/install-guide/standalone#installation

**Comment by chanmmn** [comment]
OK, I can see it after the installation. Thanks.
