### ISSUE TITLE
Tensorial product not displaying (in localized versions)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/quantum-docs-pr#921]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/quantum-docs-pr.it-IT/issues/3 
The issue replicates in the localized versions.

After further investigation, we concluded this is due to a source issue. It has been escalated in Loc Issue #240894 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb830cc-7d9b-c13e-4652-115352ea1e29
* Version Independent ID: f9484b57-1dc8-06a9-ac6d-cdc7c4769981
* Content: [Linear algebra for quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/overview/algebra-for-quantum-computing)
* Content Source: [articles/overview/algebra-for-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/overview/algebra-for-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by Bradben** [comment]
Fixed with LaTeX localization issue #860
