### ISSUE TITLE
Qubit measured by Machine Learning Classifier

### ISSUE THREAD

**Issue by magula** [MicrosoftDocs/quantum-docs-pr#928]
It seems that the example classifier circuit shows the wrong qubit being measured. The qubit measured is always the last one, according to [this](https://github.com/microsoft/QuantumLibraries/blob/master/MachineLearning/src/Private.qs) and [this](https://github.com/microsoft/QuantumLibraries/blob/bb75af3caa54b99b6e68989fe9fb1de0cc6d0b65/MachineLearning/src/Classification.qs#L50) source code. (And otherwise, the last two rotations in the example would be meaningless, too.) Furthermore, I believe the documentation should mention which qubit is measured.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51651189-8ef0-2e9e-cf38-44c780602bc2
* Version Independent ID: 2127b8ce-d4d8-da8d-033f-69db92b9331d
* Content: [Design your own classifier with the QDK - Microsoft Quantum](https://docs.microsoft.com/en-ca/quantum/libraries/machine-learning/design#how-to-build-a-classifier-with-q)
* Content Source: [articles/libraries/machine-learning/design.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/libraries/machine-learning/design.md)
* Product: **quantum**
* GitHub Login: @geduardo
* Microsoft Alias: **v-edsanc@microsoft.com**

**Comment by geduardo** [comment]
Hi @magula, thank you for pointing this out. You're right, the partial information accessible through measurements on the 1st qubit remains unaffected by just local operations on the second qubit. I'll create a PR to fix the figure and comment on the qubit measurement.
