### ISSUE TITLE
Description of `apply / within` as part of control flow.

### ISSUE THREAD

**Issue by msoeken** [MicrosoftDocs/quantum-docs-pr#939]
Conjugation is currently described as part of [Operations and functions](https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/operations-functions). I would have expected it (also) as part of the [Control flow](https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/control-flow), where all other control flow constructs are described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 704e68ff-365d-99ee-f7b3-7c1342cbbc6b
* Version Independent ID: f997d8f0-c8dc-5fd9-2921-fadcfda3c5b6
* Content: [Operations and functions in Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/operations-functions)
* Content Source: [articles/user-guide/using-qsharp/operations-functions.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/using-qsharp/operations-functions.md)
* Product: **quantum**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec@microsoft.com**

**Comment by cgranade** [comment]
I wonder if it may be reasonable to have a section on Q# keywords, similar to how the [Python language reference](https://docs.python.org/3/reference/index.html) lists different kinds of statements, or to how the [C# language reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/) has a page for each keyword to help with searchability?

**Comment by msoeken** [comment]
@cgranade I really like this idea. Also, I keep on entering keywords into the TOC search box, even though it only filters through the TOC titles. So I guess if they had separate pages showing up in the TOC, they'd be in that search automatically.

**Comment by cgranade** [comment]
+@KittyYeungQ, @bettinaheim for discussion

**Comment by gillenhaalb** [comment]
Figure a keyword list might be a good addition to the Quick Reference pages in the user guide. Did a quick scan through and came out with these keywords below. Figure this is a decent place to discuss, let me know if I'm missing anything. (The bold titles are just loosely what they relate to for our sake here, not a suggestion for the quick ref page structure).

**Types:** 
- Int, BigInt, Double, Bool, Range, String, Unit, Qubit, Pauli, Result
- true, false, PauliI, PauliX, PauliY, PauliZ, One, Zero

**Vars:**
- new, let, set, mutable, 

- operation, function, newtype

**Ops:**
- Adjoint, Controlled, Controlled Adjoint
- is, Adj, Ctl, Adj + Ctl
- Specializations:
	- **tags:** body, adjoint, controlled, controlled adjoint
	- **directives:** intrinsic, distribute, invert, self, auto
- return
- apply, within
- _ (partial application symbol)

**Control flow**
- for, in
- if, elif, else, while 
- repeat, until, fixup
- fail

**Qubits:**
- using, borrowing,

**Namespace:**
- namespace, open, as, 

**Attributes:**
- @Test("..."), @EntryPoint(), 

**Operator symbols:**
https://docs.microsoft.com/en-us/quantum/user-guide/language/expressions#operator-precedence

**Comment by crazy4pi314** [comment]
Strong +1 to @msoeken and @cgranade I keep trying to find docs for things like `within`/`apply` and other control flow and functors that then don't come up in search and I have to try and memorize which sub pages they are on (not always where I would expect them). My memory frequently fails me especially when I am on stream 😅

**Comment by KittyYeungQ** [comment]
@msoeken @cgranade @efratshabtai Can you take a look at the above list and confirm if it looks good or missing anything?

**Comment by cgranade** [comment]
Adding @bettinaheim, since many of these are about the Q# language itself. To that effect, there's a full list of Q# keywords defined in the parser at https://github.com/microsoft/qsharp-compiler/blob/2002c55a59808d44c2fec4f862c67b5848c27816/src/QsCompiler/TextProcessor/QsKeywords.fs#L66 and https://github.com/microsoft/qsharp-compiler/blob/b77641106b8faaa9046e119dec9f704f200bce46/src/QsCompiler/DataStructures/ReservedKeywords.fs. In any case, I think the only other language-level thing that I find myself linking people to regularly is the format for documentation comments (currently at https://docs.microsoft.com/en-us/quantum/user-guide/using-qsharp/file-structure#documentation-comments, under Q# user guide → Use Q# → File structure).

**Comment by msoeken** [comment]
@KittyYeungQ I cannot see anything missing there.

**Comment by efratshabtai** [comment]
@KittyYeungQ looks good to me

**Comment by KittyYeungQ** [comment]
@gillenhaalb can you create a PR to add this?

**Comment by gillenhaalb** [comment]
@KittyYeungQ Yep, will do that now. A few clarifications before I start:

1. I'll be moving the Conjugation section to Control Flow. @geduardo mentioned the lack of documentation on it (i.e. `within/apply` statements) in #1034. Could you clarify, Eduardo, if you were referring to the explanation being insufficient, or simply being in an odd location? 

2. I'll be creating a quick-ref page containing all the constructs/keywords. @cgranade @crazy4pi314 @msoeken, would that be sufficient, or would you also prefer a separate page each (to improve searchability)?

**Comment by geduardo** [comment]
The explanation being insufficient. I can't find any explanation for the functioning and purpose of the keywords `apply` and `within`.

**Comment by geduardo** [comment]
For example, in the first code block of this section on Pauli measurements: https://docs.microsoft.com/en-us/quantum/concepts/pauli-measurements
the keywords are used in a context slightly different from what is stated in the documentation.

**Comment by gillenhaalb** [comment]
@geduardo I think the confusion (w.r.t. that example specifically) comes from their use being somewhat poorly described there (i.e. on the Pauli page). As far as I can tell from the documentation (Conjugation section), a block of 
```
within{
Op1(target)
}
apply{
Op2(target)
}
```
corresponds to applying `Op1`, then `Op2`, and then `adjoint Op1` at the end. 

So, what's actually happening in the Pauli code block is that it's applying `H S^dag`, then measuring in Z, and _then_ applying `(H S^dag)^dag`.

**Comment by cgranade** [comment]
> 2. I'll be creating a quick-ref page containing all the constructs/keywords. @cgranade @crazy4pi314 @msoeken, would that be sufficient, or would you also prefer a separate page for each (to improve searchability)? The latter would require a little more discussion into what/how much should be on each page.

I think the searchability argument is a pretty good one for splitting things up further as a reference. Can we compare to what other docs.ms docsets do? Taking a quick look:

- C#: one page per keyword (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/abstract)
- F#: combined keyword reference page (https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/keyword-reference)
- C++: combined keyword reference page, with many keywords getting listed on additional pages (https://docs.microsoft.com/en-us/cpp/cpp/keywords-cpp?view=vs-2019)
- PowerShell: combined keyword reference page, with many keywords getting listed on additional pages  (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-7)
- Kusto: one page per keyword (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/)
- T-SQL: one page per keyword (https://docs.microsoft.com/en-us/sql/t-sql/language-elements/language-elements-transact-sql?view=sql-server-ver15)
- VB.NET: one page per keyword (https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/)

**Comment by cgranade** [comment]
> So, what's actually happening in the Pauli code block is that it's applying `H S^dag`, then measuring in Z, and _then_ applying `(H S^dag)^dag`.

That's correct; the `within` part of `MeasureY` ensures that the 𝑌-basis is mapped to the 𝑍-basis, then the `apply` part performs the measurement. The final part, the adjoint of the `within` part, ensures that the post-measurement state is what you would expect from a 𝑌-basis measurement by mapping the 𝑍-basis post-measurement state _back_ to the 𝑌-basis.

**Comment by crazy4pi314** [comment]
> > 1. I'll be creating a quick-ref page containing all the constructs/keywords. @cgranade @crazy4pi314 @msoeken, would that be sufficient, or would you also prefer a separate page for each (to improve searchability)? The latter would require a little more discussion into what/how much should be on each page.
> 
> I think the searchability argument is a pretty good one for splitting things up further as a reference. Can we compare to what other docs.ms docsets do? Taking a quick look:

I strongly agree with the searchability concern. I am often working (or on stream) and want to look up the docs for things like `within`/`apply` to link folks to and if it does not come up in the search box on the docs page I find it extremely hard to find.

**Comment by gillenhaalb** [comment]
@cgranade @crazy4pi314 Thanks for the input (and links, etc.). The benefit in searchability does sound substantial---I think I'll go ahead with that route.

I'll make a small PR moving the conjugations section to Control Flow, and then a separate one for the keywords pages. They'll start out relatively minimalist just to go ahead and have them all in place, and we can then discuss more in the PR what info the pages should/shouldn't have.

**Comment by cgranade** [comment]
> @cgranade @crazy4pi314 Thanks for the input (and links, etc.). The benefit in searchability does sound substantial---I think I'll go ahead with that route.

No worries, happy to help! Thanks for taking this on!

> I'll make a small PR moving the conjugations section to Control Flow, and then a separate one for the keywords pages. They'll start out relatively minimalist just to go ahead and have them all in place, and we can then discuss more in the PR what info the pages should/shouldn't have.

Sounds like a good plan, please let me know if I can help. One suggestion I'd have as they get past the minimal stage is to include concrete examples as much as possible; ideally said examples would be pulled from the samples repo so that we can unit test and make sure that those samples stay correct as the Q# language evolves. With the new ability to draw from Jupyter Notebooks, we may be able to tie that to @guenp's suggestion at https://github.com/microsoft/Quantum/issues/422 if we format the Intro to Q# sample as a Q# notebook.

**Comment by geduardo** [comment]
I think this issue was solved with the new language repo.
