### ISSUE TITLE
Example code has warning

### ISSUE THREAD

**Issue by jamers99** [MicrosoftDocs/quantum-docs-pr#945]
The example for the random number generator has a warning on line 22
`SampleRandomNumberInRange(max)`

**_This expression may be short-circuited, and operation calls may not be executed._**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7575d10-c405-8e24-3487-008d2338b756
* Version Independent ID: 030f289f-4280-def3-598b-615883282486
* Content: [Create a Quantum Random Number Generator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/tutorials/quantum-random-number-generator?tabs=tabid-qsharp)
* Content Source: [articles/tutorials/quantum-random-number-generator.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/tutorials/quantum-random-number-generator.md)
* Product: **quantum**
* GitHub Login: @bromeg
* Microsoft Alias: **megbrow@microsoft.com**

**Comment by geduardo** [comment]
Thank you for filling this issue @jamers99, I can reproduce the warning.

@cgranade, do you have any idea of why this warning is happening?

**Comment by cgranade** [comment]
Thanks for the feedback, @jamers99!

@geduardo: It comes down to the following snippet:
```Q#
    return sample > max
           ? SampleRandomNumberInRange(max)
           | sample;
```
That statement is used to repeat the sampling if `sample` was too large. The warning lets us know that in the case that `sample <= max`, the `? |` operator will be short-circuited such that the `SampleRandomNumberInRange` operation isn't called.

**Comment by geduardo** [comment]
Ah, I see, so it's intentional. Thanks, @cgranade. 

Suggestion: maybe we should rephrase the warning since it created confusion for at least two people (@jamers99 and me), e.g. I didn't find clear what short-circuited meant in this context.
