### ISSUE TITLE
Broken link in relnotes for 0.12

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/quantum-docs-pr#951]
The link in the second bullet for the [0.12 release notes](https://docs.microsoft.com/en-us/quantum/resources/relnotes#version-01220070124) is broken. " Microsoft.Quantum.Synthesis namespace" links to [xref:microsoft.quantum.synthesis](xref:microsoft.quantum.synthesis) when it should link to [https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.synthesis](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.synthesis).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88063b8-bb4f-1d76-7ea9-d5ca7f28cbfd
* Version Independent ID: 22d0cb8d-9272-7243-8052-e16c107581a4
* Content: [Quantum Development Kit Release Notes - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/resources/relnotes#version-01220070124)
* Content Source: [articles/resources/relnotes.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/resources/relnotes.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by Bradben** [comment]
Thanks for catching that -

The syntax in the markdown looks fine, but it doesn't look like the href formed correctly in the html during build. 

New functions and operations in the <a href="xref:microsoft.quantum.synthesis" data-linktype="external"><code>Microsoft.Quantum.Synthesis</code> namespace</a> for coherently ….</li>

I'm going to run it through build again and investigate from there.
