### ISSUE TITLE
Update targets section in Q# user guide to show how to change targets directly from the CLI

### ISSUE THREAD

**Issue by geduardo** [MicrosoftDocs/quantum-docs-pr#954]
We need to add an explanation on how to use the command line to change the targets (e.g. how to use the ResourceEstimator). 
Step:
1. Assign the option from the CLI using Dotnet commands: `--simulator ResourcesEstimator`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb2344ee-3afb-541f-65c2-a413b98c0c69
* Version Independent ID: 520e0a3a-3106-b422-48bf-1b15af0ad1b6
* Content: [Quantum Development Kit Resources Estimator - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/machines/resources-estimator)
* Content Source: [articles/user-guide/machines/resources-estimator.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/machines/resources-estimator.md)
* Product: **quantum**
* GitHub Login: @anpaz-msft
* Microsoft Alias: **anpaz@microsoft.com**

**Comment by gillenhaalb** [comment]
@geduardo I think this has been addressed/merged in the most recent copy-edits by Brad (#944 and #942). Each simulator page presents those details and also refers to the "Ways to run a Q# program" for further details

**Comment by geduardo** [comment]
Yup, that fixes this issue. Closing!
