### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by gonzrubio** [MicrosoftDocs/quantum-docs-pr#964]
"For example, consider a phase orcale" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4959bf-caf5-9030-73a2-3910b8a0788e
* Version Independent ID: 3a6ff78b-19a7-f824-5783-8015c047b6bc
* Content: [Quantum oracles - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/oracles)
* Content Source: [articles/concepts/oracles.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/oracles.md)
* Product: **quantum**
* GitHub Login: @cgranade
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by geduardo** [comment]
Thanks for filling the issue @gonzrubio. I created a PR to fix the typo: https://github.com/MicrosoftDocs/quantum-docs-pr/pull/965
