### ISSUE TITLE
Unable to find package Microsoft.Quantum.Standard 

### ISSUE THREAD

**Issue by jd62480** [MicrosoftDocs/quantum-docs-pr#973]
[Enter feedback here]

After following the instructions, I get the following error when running python -c "import qsharp"

One or more errors occurred. (Unable to find package 'Microsoft.Quantum.Standard'. Existing packages must be restored before performing an install or update.)

From a Anaconda Powershell Prompt (anaconda3) I ran 
(qsharp-env) PS D:\Nuget> dotnet nuget list source
Registered Sources:
  1.  Package source 1 [Enabled]
      d:\Nuget\microsoft.quantum.compiler.0.12.20070124

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a7f7964-eb2b-502d-470d-91f826aea2ff
* Version Independent ID: d74f059a-e3a3-29e8-ba53-cef7c831f010
* Content: [Develop with Q# Jupyter Notebooks - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/install-jupyter?tabs=tabid-conda)
* Content Source: [articles/quickstarts/install-jupyter.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/install-jupyter.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by rmshaffer** [comment]
@jd62480 it looks like nuget.org isn't in your nuget source list for some reason. Could you try adding it? e.g., run:

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

and then retry `python -c "import qsharp"`.

**Comment by jd62480** [comment]
Running this command solved the jupyter notebook issue.

**Comment by rmshaffer** [comment]
Great, thanks for confirming!
