### ISSUE TITLE
MS QDK for VS Code

### ISSUE THREAD

**Issue by jd62480** [MicrosoftDocs/quantum-docs-pr#974]
[Enter feedback here]

After following the instructions, I get:

Project creation failed. The Q# project templates may not be installed.

From a terminal within VS Code, I ran 
PS D:\Projects> dotnet nuget list source

Registered Sources:
  1.  Package source 1 [Enabled]
      d:\Nuget\microsoft.quantum.compiler.0.12.20070124

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e509ca-7867-e8f0-45f1-bb20d27ad232
* Version Independent ID: a6a281f8-53e0-8bdb-2b6e-8228fc2204f2
* Content: [Develop with Q# command line applications - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/quickstarts/install-command-line?tabs=tabid-vscode)
* Content Source: [articles/quickstarts/install-command-line.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/quickstarts/install-command-line.md)
* Product: **quantum**
* GitHub Login: @KittyYeungQ
* Microsoft Alias: **kitty**

**Comment by rmshaffer** [comment]
Looks like a similar issue to #973. It looks like nuget.org isn't in your nuget source list for some reason. Could you try adding it? e.g., run:

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

and then retry installing the project templates and then creating a project.

**Comment by jd62480** [comment]
I added nuget.org and I get the same issue in Visual Studio Code.

**Comment by rmshaffer** [comment]
Does it work if you first choose "Q#: Install project templates", followed by "Q#: Create new project"?

![image](https://user-images.githubusercontent.com/3620100/87866481-34890280-c937-11ea-9102-bd8a2b065f45.png)

**Comment by jd62480** [comment]
I enable the QDK, install the templates (pop-up reports that they were
successfully added), and then try to create a project. I consistently
cannot create the project even after adding nuget.org.

**Comment by KittyYeungQ** [comment]
Hi @jd62480 would you mind sharing which version of QDK and VS Code you are using?

**Comment by jd62480** [comment]
VS Code About:

Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

MS QDK: v0.12.20070124

dotnet nuget list source

Registered Sources:
  1.  Package source 1 [Enabled]
      d:\Nuget\microsoft.quantum.compiler.0.12.20070124
  2.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json

**Comment by jd62480** [comment]
Update:

Step 1: I updated my Windows 10 machine with "July 21, 2020-KB4562900 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Windows 10 Version 1903 and Windows Server 1903 RTM and Windows 10, version 1909 and Windows Server, version 1909"

Step 2: I successfully installed templates and created a new project. 

Step 3: I removed the Registered Source "Package source 1" (see earlier post) by running on a terminal PS "Unregister-PackageSource -Source "Package source 1""

Step 4" I ran from the terminal "dotnet run" and got "Hello quantum world!"

Success!!

**Comment by KittyYeungQ** [comment]
Great! Thank you for the update.
