### ISSUE TITLE
temporary fix for German page localization

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#982]
We have encountered something strange with translation: For some reason the German page of our docs translates the Q# Style Guide with "F# Stil-Handbuch" (https://docs.microsoft.com/de-de/quantum/resources/contributing/style-guide?tabs=guidance): Q# becomes F# for some reason. The same seems to be the case for a couple of other places, but not everywhere. I'd expect that other pages are affected as well. 

Since this issue is introduced by are Machine Translation engine, it will take a while to get it fixed.

Temporary fix: “Q#” in the no-loc tag which will prevent it from getting localized

**Comment by KittyYeungQ** [comment]
@gillenhaalb can you please let me know when you add “Q#” to the no-loc tag list on https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md article ? There is an active production issue pending this update.

**Comment by gillenhaalb** [comment]
@KittyYeungQ Sorry for the delay. I forgot to ping you with a question I had when I first saw it: should I only make the change on this single page, or just go ahead and add the no-loc tag list to all documentation pages? (For this fix specifically they would only include "Q#", not the full LaTeX stuff we're still working on).

**Comment by KittyYeungQ** [comment]
We have found a similar issue with the Spanish page. The temporary solution is suggested by the docs localization team. Do you think it will work?

In the Spanish translations for our documentation:
https://docs.microsoft.com/es-es/quantum/resources/contributing/style-guide?tabs=guidance
https://docs.microsoft.com/es-mx/quantum/resources/contributing/style-guide?tabs=guidance

The term Q# is being translated as if it were "Q&A" resulting in "preguntas y respuestas", which makes part of the content nonsensical.

**Comment by gillenhaalb** [comment]
@KittyYeungQ Worth a shot. Before I go through and do it all, just want to confirm that that's a "yes" to adding it to every page?

**Comment by KittyYeungQ** [comment]
Yes
